<?php

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.42.3
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Test\Api;

use Hostinger\Configuration;
use Hostinger\ApiException;
use Hostinger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class AgencyHostingPHPApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for listAvailablePHPVersionsForAWebsiteV1
     *
     * List available PHP versions for a website.
     *
     */
    public function testListAvailablePHPVersionsForAWebsiteV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAvailablePHPVersionsForAnOrderV1
     *
     * List available PHP versions for an order.
     *
     */
    public function testListAvailablePHPVersionsForAnOrderV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPHPExtensionsForAWebsiteV1
     *
     * List PHP extensions for a website.
     *
     */
    public function testListPHPExtensionsForAWebsiteV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPHPOptionsForAWebsiteV1
     *
     * List PHP options for a website.
     *
     */
    public function testListPHPOptionsForAWebsiteV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceWebsitePHPExtensionsV1
     *
     * Replace website PHP extensions.
     *
     */
    public function testReplaceWebsitePHPExtensionsV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for replaceWebsitePHPOptionsV1
     *
     * Replace website PHP options.
     *
     */
    public function testReplaceWebsitePHPOptionsV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWebsitePHPVersionV1
     *
     * Update website PHP version.
     *
     */
    public function testUpdateWebsitePHPVersionV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
