<?php

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.8.2
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Test\Api;

use Hostinger\Configuration;
use Hostinger\ApiException;
use Hostinger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class AgencyHostingDomainsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for changeAgencyPlanWebsiteDomainV1
     *
     * Change Agency Plan website domain.
     *
     */
    public function testChangeAgencyPlanWebsiteDomainV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for linkDomainToAgencyPlanWebsiteV1
     *
     * Link domain to Agency Plan website.
     *
     */
    public function testLinkDomainToAgencyPlanWebsiteV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAgencyPlanDomainsV1
     *
     * List Agency Plan domains.
     *
     */
    public function testListAgencyPlanDomainsV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for unlinkDomainFromAgencyPlanWebsiteV1
     *
     * Unlink domain from Agency Plan website.
     *
     */
    public function testUnlinkDomainFromAgencyPlanWebsiteV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
