<?php

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.19.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Test\Api;

use Hostinger\Configuration;
use Hostinger\ApiException;
use Hostinger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class AgencyHostingDatabasesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createAgencyPlanWebsiteDatabaseUserV1
     *
     * Create Agency Plan website database user.
     *
     */
    public function testCreateAgencyPlanWebsiteDatabaseUserV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createAgencyPlanWebsiteDatabaseV1
     *
     * Create Agency Plan website database.
     *
     */
    public function testCreateAgencyPlanWebsiteDatabaseV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAgencyPlanWebsiteDatabaseUserV1
     *
     * Delete Agency Plan website database user.
     *
     */
    public function testDeleteAgencyPlanWebsiteDatabaseUserV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAgencyPlanWebsiteDatabaseV1
     *
     * Delete Agency Plan website database.
     *
     */
    public function testDeleteAgencyPlanWebsiteDatabaseV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAgencyPlanWebsiteDatabasesV1
     *
     * List Agency Plan website databases.
     *
     */
    public function testListAgencyPlanWebsiteDatabasesV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
