<?php

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.35.1
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Test\Api;

use Hostinger\Configuration;
use Hostinger\ApiException;
use Hostinger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class DomainsMoveApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for acceptIncomingDomainMoveV1
     *
     * Accept incoming domain move.
     *
     */
    public function testAcceptIncomingDomainMoveV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for cancelOutgoingDomainMoveV1
     *
     * Cancel outgoing domain move.
     *
     */
    public function testCancelOutgoingDomainMoveV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getIncomingDomainMoveListV1
     *
     * Get incoming domain move list.
     *
     */
    public function testGetIncomingDomainMoveListV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getIncomingDomainMoveV1
     *
     * Get incoming domain move.
     *
     */
    public function testGetIncomingDomainMoveV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOutgoingDomainMoveListV1
     *
     * Get outgoing domain move list.
     *
     */
    public function testGetOutgoingDomainMoveListV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOutgoingDomainMoveV1
     *
     * Get outgoing domain move.
     *
     */
    public function testGetOutgoingDomainMoveV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rejectIncomingDomainMoveV1
     *
     * Reject incoming domain move.
     *
     */
    public function testRejectIncomingDomainMoveV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for startOutgoingDomainMoveV1
     *
     * Start outgoing domain move.
     *
     */
    public function testStartOutgoingDomainMoveV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
