<?php

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.50.1
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Test\Api;

use Hostinger\Configuration;
use Hostinger\ApiException;
use Hostinger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class HorizonsWebsitesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cloneWebsiteV1
     *
     * Clone website.
     *
     */
    public function testCloneWebsiteV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createWebsiteV1
     *
     * Create website.
     *
     */
    public function testCreateWebsiteV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for editWebsiteV1
     *
     * Edit website.
     *
     */
    public function testEditWebsiteV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWebsiteListV1
     *
     * Get website list.
     *
     */
    public function testGetWebsiteListV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWebsiteV1
     *
     * Get website.
     *
     */
    public function testGetWebsiteV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for publishWebsiteV1
     *
     * Publish website.
     *
     */
    public function testPublishWebsiteV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
