<?php

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.18.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Test\Api;

use Hostinger\Configuration;
use Hostinger\ApiException;
use Hostinger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class MailWebhooksApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createWebhookV1
     *
     * Create webhook.
     *
     */
    public function testCreateWebhookV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWebhookV1
     *
     * Delete webhook.
     *
     */
    public function testDeleteWebhookV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWebhookV1
     *
     * Get webhook.
     *
     */
    public function testGetWebhookV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listWebhookDeliveryLogsV1
     *
     * List webhook delivery logs.
     *
     */
    public function testListWebhookDeliveryLogsV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listWebhooksV1
     *
     * List webhooks.
     *
     */
    public function testListWebhooksV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for regenerateWebhookSecretV1
     *
     * Regenerate webhook secret.
     *
     */
    public function testRegenerateWebhookSecretV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for testWebhookV1
     *
     * Test webhook.
     *
     */
    public function testTestWebhookV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWebhookV1
     *
     * Update webhook.
     *
     */
    public function testUpdateWebhookV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
