<?php

/**
 * Hostinger API PHP SDK
 *
 * API Version: 0.1.16
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Test\Api;

use Hostinger\Configuration;
use Hostinger\ApiException;
use Hostinger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class ReachContactsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createANewContactV1
     *
     * Create a new contact.
     *
     */
    public function testCreateANewContactV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAContactV1
     *
     * Delete a contact.
     *
     */
    public function testDeleteAContactV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listContactGroupsV1
     *
     * List contact groups.
     *
     */
    public function testListContactGroupsV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listContactsV1
     *
     * List contacts.
     *
     */
    public function testListContactsV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
