<?php

/**
 * Hostinger API PHP SDK
 *
 * API Version: 0.0.16
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Test\Api;

use Hostinger\Configuration;
use Hostinger\ApiException;
use Hostinger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class VPSPublicKeysApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for attachPublicKeyV1
     *
     * Attach public key.
     *
     */
    public function testAttachPublicKeyV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createNewPublicKeyV1
     *
     * Create new public key.
     *
     */
    public function testCreateNewPublicKeyV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAPublicKeyV1
     *
     * Delete a public key.
     *
     */
    public function testDeleteAPublicKeyV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPublicKeyListV1
     *
     * Get public key list.
     *
     */
    public function testGetPublicKeyListV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
