<?php

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.62.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Test\Api;

use Hostinger\Configuration;
use Hostinger\ApiException;
use Hostinger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class VPSSSHKeysApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addVirtualMachineSSHKeysV1
     *
     * Add virtual machine SSH keys.
     *
     */
    public function testAddVirtualMachineSSHKeysV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listVirtualMachineSSHKeysV1
     *
     * List virtual machine SSH keys.
     *
     */
    public function testListVirtualMachineSSHKeysV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeVirtualMachineSSHKeysV1
     *
     * Remove virtual machine SSH keys.
     *
     */
    public function testRemoveVirtualMachineSSHKeysV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
