<?php

/**
 * Hostinger API PHP SDK
 *
 * API Version: 0.0.14
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Test\Api;

use Hostinger\Configuration;
use Hostinger\ApiException;
use Hostinger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class VPSVirtualMachineApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAttachedPublicKeysV1
     *
     * Get attached public keys.
     *
     */
    public function testGetAttachedPublicKeysV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMetricsV1
     *
     * Get metrics.
     *
     */
    public function testGetMetricsV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getVirtualMachineListV1
     *
     * Get virtual machine list.
     *
     */
    public function testGetVirtualMachineListV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getVirtualMachineV1
     *
     * Get virtual machine.
     *
     */
    public function testGetVirtualMachineV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recreateVirtualMachineV1
     *
     * Recreate virtual machine.
     *
     */
    public function testRecreateVirtualMachineV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resetHostnameV1
     *
     * Reset hostname.
     *
     */
    public function testResetHostnameV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for restartVirtualMachineV1
     *
     * Restart virtual machine.
     *
     */
    public function testRestartVirtualMachineV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setHostnameV1
     *
     * Set hostname.
     *
     */
    public function testSetHostnameV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setNameserversV1
     *
     * Set nameservers.
     *
     */
    public function testSetNameserversV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setPanelPasswordV1
     *
     * Set panel password.
     *
     */
    public function testSetPanelPasswordV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setRootPasswordV1
     *
     * Set root password.
     *
     */
    public function testSetRootPasswordV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setupNewVirtualMachineV1
     *
     * Setup new virtual machine.
     *
     */
    public function testSetupNewVirtualMachineV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for startVirtualMachineV1
     *
     * Start virtual machine.
     *
     */
    public function testStartVirtualMachineV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for stopVirtualMachineV1
     *
     * Stop virtual machine.
     *
     */
    public function testStopVirtualMachineV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
