<?php

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.13.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Test\Api;

use Hostinger\Configuration;
use Hostinger\ApiException;
use Hostinger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class WordPressInstallationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for checkIfWordPressInstallationsAreValidV1
     *
     * Check if WordPress installations are valid.
     *
     */
    public function testCheckIfWordPressInstallationsAreValidV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWordPressInstallationV1
     *
     * Delete WordPress installation.
     *
     */
    public function testDeleteWordPressInstallationV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for detectWordPressInstallationsV1
     *
     * Detect WordPress installations.
     *
     */
    public function testDetectWordPressInstallationsV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getInstallationJWTTokenV1
     *
     * Get installation JWT token.
     *
     */
    public function testGetInstallationJWTTokenV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for installWordPressV1
     *
     * Install WordPress.
     *
     */
    public function testInstallWordPressV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAvailableWordPressCoreUpdatesV1
     *
     * List available WordPress core updates.
     *
     */
    public function testListAvailableWordPressCoreUpdatesV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listWordPressInstallationsV1
     *
     * List WordPress installations.
     *
     */
    public function testListWordPressInstallationsV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for showWordPressCoreVersionV1
     *
     * Show WordPress core version.
     *
     */
    public function testShowWordPressCoreVersionV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWordPressCoreV1
     *
     * Update WordPress core.
     *
     */
    public function testUpdateWordPressCoreV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
