<?php

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.11.1
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Test\Api;

use Hostinger\Configuration;
use Hostinger\ApiException;
use Hostinger\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class WordPressThemesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for activateWordPressThemeV1
     *
     * Activate WordPress theme.
     *
     */
    public function testActivateWordPressThemeV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for installWordPressThemeV1
     *
     * Install WordPress theme.
     *
     */
    public function testInstallWordPressThemeV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listInstalledWordPressThemesV1
     *
     * List installed WordPress themes.
     *
     */
    public function testListInstalledWordPressThemesV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listWordPressThemesV1
     *
     * List WordPress themes.
     *
     */
    public function testListWordPressThemesV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uninstallWordPressThemesV1
     *
     * Uninstall WordPress themes.
     *
     */
    public function testUninstallWordPressThemesV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWordPressThemesV1
     *
     * Update WordPress themes.
     *
     */
    public function testUpdateWordPressThemesV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
