<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.20.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class AgencyHostingV1OrdersPlanResource 
{

    /**
     * @var string|null $name
     */
    private ?string $name = null;

    /**
     * @var string|null $key
     */
    private ?string $key = null;

    /**
    * @return string|null
    */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string|null $name Plan display name
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getKey(): ?string
    {
        return $this->key;
    }

    /**
     * @param string|null $key Plan key
     */
    public function setKey(?string $key): self
    {
        $this->key = $key;

        return $this;
    }
}

