<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.8.1
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class AgencyHostingV1WebsitesWebsiteSettingsResource 
{

    /**
     * @var \Hostinger\Model\AgencyHostingV1WebsitesWebsitePhpSettingsResource|null $php
     */
    private ?\Hostinger\Model\AgencyHostingV1WebsitesWebsitePhpSettingsResource $php = null;

    /**
    * @return \Hostinger\Model\AgencyHostingV1WebsitesWebsitePhpSettingsResource|null
    */
    public function getPhp(): ?\Hostinger\Model\AgencyHostingV1WebsitesWebsitePhpSettingsResource
    {
        return $this->php;
    }

    /**
     * @param \Hostinger\Model\AgencyHostingV1WebsitesWebsitePhpSettingsResource|null $php php
     */
    public function setPhp(?\Hostinger\Model\AgencyHostingV1WebsitesWebsitePhpSettingsResource $php): self
    {
        $this->php = $php;

        return $this;
    }
}

