<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.42.4
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class AgencyHostingV1OrdersDiskUsageMetricsMetricsResource 
{

    /**
     * @var \Hostinger\Model\AgencyHostingV1OrdersDiskUsageMetricsLimitsResource|null $limits
     */
    private ?\Hostinger\Model\AgencyHostingV1OrdersDiskUsageMetricsLimitsResource $limits;

    /**
     * @var \Hostinger\Model\AgencyHostingV1OrdersDiskUsageMetricsMetricResource[]|null $metrics
     */
    private ?array $metrics;

    /**
    * @return \Hostinger\Model\AgencyHostingV1OrdersDiskUsageMetricsLimitsResource|null
    */
    public function getLimits(): ?\Hostinger\Model\AgencyHostingV1OrdersDiskUsageMetricsLimitsResource
    {
        return $this->limits;
    }

    /**
     * @param \Hostinger\Model\AgencyHostingV1OrdersDiskUsageMetricsLimitsResource|null $limits limits
     */
    public function setLimits(?\Hostinger\Model\AgencyHostingV1OrdersDiskUsageMetricsLimitsResource $limits): self
    {
        $this->limits = $limits;

        return $this;
    }
    /**
    * @return \Hostinger\Model\AgencyHostingV1OrdersDiskUsageMetricsMetricResource[]|null
    */
    public function getMetrics(): ?array
    {
        return $this->metrics;
    }

    /**
     * @param \Hostinger\Model\AgencyHostingV1OrdersDiskUsageMetricsMetricResource[]|null $metrics Array of [`AgencyHosting.V1.Orders.DiskUsageMetrics.MetricResource`](#model/agencyhostingv1ordersdiskusagemetricsmetricresource)
     */
    public function setMetrics(?array $metrics): self
    {
        $this->metrics = $metrics;

        return $this;
    }
}

