<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.14.1
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class AgencyHostingV1DatacentersDatacenterResource 
{

    /**
     * @var string $title
     */
    private string $title;

    /**
     * @var string $code
     */
    private string $code;

    /**
     * @var string $country
     */
    private string $country;

    /**
     * @var \Hostinger\Model\AgencyHostingV1DatacentersCoordinatesResource $coordinates
     */
    private \Hostinger\Model\AgencyHostingV1DatacentersCoordinatesResource $coordinates;

    /**
     * @var string $pingerUrl
     */
    private ?string $pingerUrl = null;

    /**
    * @return string
    */
    public function getTitle(): string
    {
        return $this->title;
    }

    /**
     * @param string $title Datacenter title
     */
    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }
    /**
    * @return string
    */
    public function getCode(): string
    {
        return $this->code;
    }

    /**
     * @param string $code Datacenter code
     */
    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }
    /**
    * @return string
    */
    public function getCountry(): string
    {
        return $this->country;
    }

    /**
     * @param string $country Datacenter country code
     */
    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }
    /**
    * @return \Hostinger\Model\AgencyHostingV1DatacentersCoordinatesResource
    */
    public function getCoordinates(): \Hostinger\Model\AgencyHostingV1DatacentersCoordinatesResource
    {
        return $this->coordinates;
    }

    /**
     * @param \Hostinger\Model\AgencyHostingV1DatacentersCoordinatesResource $coordinates coordinates
     */
    public function setCoordinates(\Hostinger\Model\AgencyHostingV1DatacentersCoordinatesResource $coordinates): self
    {
        $this->coordinates = $coordinates;

        return $this;
    }
    /**
    * @return string
    */
    public function getPingerUrl(): ?string
    {
        return $this->pingerUrl;
    }

    /**
     * @param string $pingerUrl URL you can ping to measure round-trip latency to this datacenter. Compare the measured latency across datacenters to identify the nearest one (lowest ping) for your website. Null when no online server is currently available to measure against.
     */
    public function setPingerUrl(?string $pingerUrl): self
    {
        $this->pingerUrl = $pingerUrl;

        return $this;
    }
}

