<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.6.2
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class AgencyHostingV1FilesUploadUrlResource 
{

    /**
     * @var string $url
     */
    private string $url;

    /**
     * @var string $authKey
     */
    private string $authKey;

    /**
     * @var string $restAuthKey
     */
    private string $restAuthKey;

    /**
    * @return string
    */
    public function getUrl(): string
    {
        return $this->url;
    }

    /**
     * @param string $url The TUS upload endpoint URL to send upload requests to
     */
    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }
    /**
    * @return string
    */
    public function getAuthKey(): string
    {
        return $this->authKey;
    }

    /**
     * @param string $authKey Authentication token to pass as the `X-Auth` header in TUS upload requests
     */
    public function setAuthKey(string $authKey): self
    {
        $this->authKey = $authKey;

        return $this;
    }
    /**
    * @return string
    */
    public function getRestAuthKey(): string
    {
        return $this->restAuthKey;
    }

    /**
     * @param string $restAuthKey Authentication token to pass as the `X-Auth-Rest` header in TUS upload requests
     */
    public function setRestAuthKey(string $restAuthKey): self
    {
        $this->restAuthKey = $restAuthKey;

        return $this;
    }
}

