<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.18.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class AgencyHostingV1WebsitesWebsiteStagingRootResource 
{

    /**
     * @var string|null $uid
     */
    private ?string $uid;

    /**
    * @return string|null
    */
    public function getUid(): ?string
    {
        return $this->uid;
    }

    /**
     * @param string|null $uid UID of the website this is a staging environment of
     */
    public function setUid(?string $uid): self
    {
        $this->uid = $uid;

        return $this;
    }
}

