<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.54.1
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class AgencyHostingV1SslSslStatusResource 
{
    /**
     * @var string
     */
    public const STATUS_NOT_INSTALLED = 'not_installed';
    /**
     * @var string
     */
    public const STATUS_INSTALLING = 'installing';
    /**
     * @var string
     */
    public const STATUS_FAILED = 'failed';
    /**
     * @var string
     */
    public const STATUS_ACTIVE = 'active';
    /**
     * @var string
     */
    public const STATUS_EXPIRED = 'expired';

    /**
     * @var string $status
     */
    private string $status;

    /**
     * @var bool $isCustom
     */
    private bool $isCustom;

    /**
     * @var \DateTime $expiresAt
     */
    private ?\DateTime $expiresAt = null;

    /**
    * @return string
    */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * @param string $status `installing` while a certificate setup is running or retrying, `active` when a valid certificate is in place (uploaded, platform-issued, or a lifetime certificate bought for the domain), `failed` when the last setup gave up and no valid certificate is in place, `expired` when the certificate has run out, `not_installed` when the domain has no certificate and no setup process.
     */
    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }
    /**
    * @return bool
    */
    public function getIsCustom(): bool
    {
        return $this->isCustom;
    }

    /**
     * @param bool $isCustom Whether the certificate was uploaded by the customer instead of issued or sold by the platform.
     */
    public function setIsCustom(bool $isCustom): self
    {
        $this->isCustom = $isCustom;

        return $this;
    }
    /**
    * @return \DateTime
    */
    public function getExpiresAt(): ?\DateTime
    {
        return $this->expiresAt;
    }

    /**
     * @param \DateTime $expiresAt End of the validity period of the certificate in place; null when there is none or the uploaded certificate carries no expiry.
     */
    public function setExpiresAt(?\DateTime $expiresAt): self
    {
        $this->expiresAt = $expiresAt;

        return $this;
    }
}

