<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.15.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class AgencyHostingV1WebsitesWordPressInstallResource 
{

    /**
     * @var string|null $domain
     */
    private ?string $domain;

    /**
     * @var string|null $title
     */
    private ?string $title;

    /**
     * @var string|null $language
     */
    private ?string $language;

    /**
     * @var bool|null $isConfigLocked
     */
    private ?bool $isConfigLocked;

    /**
     * @var \DateTime|null $createdAt
     */
    private ?\DateTime $createdAt;

    /**
    * @return string|null
    */
    public function getDomain(): ?string
    {
        return $this->domain;
    }

    /**
     * @param string|null $domain WordPress domain
     */
    public function setDomain(?string $domain): self
    {
        $this->domain = $domain;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string|null $title WordPress title
     */
    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getLanguage(): ?string
    {
        return $this->language;
    }

    /**
     * @param string|null $language WordPress language
     */
    public function setLanguage(?string $language): self
    {
        $this->language = $language;

        return $this;
    }
    /**
    * @return bool|null
    */
    public function getIsConfigLocked(): ?bool
    {
        return $this->isConfigLocked;
    }

    /**
     * @param bool|null $isConfigLocked WordPress configuration lock status
     */
    public function setIsConfigLocked(?bool $isConfigLocked): self
    {
        $this->isConfigLocked = $isConfigLocked;

        return $this;
    }
    /**
    * @return \DateTime|null
    */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime|null $createdAt Creation date
     */
    public function setCreatedAt(?\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

