<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.12.2
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class AgencyHostingV1WebsitesWebsiteOrderPlanResource 
{

    /**
     * @var string|null $name
     */
    private ?string $name = null;

    /**
     * @var \Hostinger\Model\AgencyHostingV1WebsitesWebsiteOrderPlanResourceParameters|null $parameters
     */
    private ?\Hostinger\Model\AgencyHostingV1WebsitesWebsiteOrderPlanResourceParameters $parameters;

    /**
    * @return string|null
    */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string|null $name Plan name
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }
    /**
    * @return \Hostinger\Model\AgencyHostingV1WebsitesWebsiteOrderPlanResourceParameters|null
    */
    public function getParameters(): ?\Hostinger\Model\AgencyHostingV1WebsitesWebsiteOrderPlanResourceParameters
    {
        return $this->parameters;
    }

    /**
     * @param \Hostinger\Model\AgencyHostingV1WebsitesWebsiteOrderPlanResourceParameters|null $parameters parameters
     */
    public function setParameters(?\Hostinger\Model\AgencyHostingV1WebsitesWebsiteOrderPlanResourceParameters $parameters): self
    {
        $this->parameters = $parameters;

        return $this;
    }
}

