<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.32.1
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class BillingV1SubscriptionRenewalRenewRequest 
{

    /**
     * @var int|null $paymentMethodId
     */
    private ?int $paymentMethodId;

    /**
     * @var mixed[]|null $coupons
     */
    private ?array $coupons;

    /**
    * @return int|null
    */
    public function getPaymentMethodId(): ?int
    {
        return $this->paymentMethodId;
    }

    /**
     * @param int|null $paymentMethodId Payment method ID, default will be used if not provided
     */
    public function setPaymentMethodId(?int $paymentMethodId): self
    {
        $this->paymentMethodId = $paymentMethodId;

        return $this;
    }
    /**
    * @return mixed[]|null
    */
    public function getCoupons(): ?array
    {
        return $this->coupons;
    }

    /**
     * @param mixed[]|null $coupons Discount coupon codes
     */
    public function setCoupons(?array $coupons): self
    {
        $this->coupons = $coupons;

        return $this;
    }
}

