<?php
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 0.0.96
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Hostinger\ObjectSerializer;

/**
 * @implements ArrayAccess<string, mixed>
 */
class BillingV1SubscriptionSubscriptionResource 
{
    /**
     * @param string $id
     * @param string $name
     * @param string $status
     * @param int $billingPeriod
     * @param string $billingPeriodUnit
     * @param string $currencyCode
     * @param int $totalPrice
     * @param int $renewalPrice
     * @param bool $isAutoRenewed
     * @param \DateTime $createdAt
     * @param \DateTime|null $expiresAt
     * @param \DateTime|null $nextBillingAt
     */
    protected static $openAPIModelName = 'BillingV1SubscriptionSubscriptionResource';
    public function __construct(
        private $id,
        private $name,
        private $status,
        private $billingPeriod,
        private $billingPeriodUnit,
        private $currencyCode,
        private $totalPrice,
        private $renewalPrice,
        private $isAutoRenewed,
        private $createdAt,
        private $expiresAt = null,
        private $nextBillingAt = null,
    ) {
    }

    /**
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param string $id
     *
     * @return self
     */
    public function setId($id): self
    {
        $this->id = $id;

        return $this;
    }
    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     *
     * @return self
     */
    public function setName($name): self
    {
        $this->name = $name;

        return $this;
    }
    /**
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param string $status
     *
     * @return self
     */
    public function setStatus($status): self
    {
        $this->status = $status;

        return $this;
    }
    /**
     * @return int
     */
    public function getBillingPeriod()
    {
        return $this->billingPeriod;
    }

    /**
     * @param int $billingPeriod
     *
     * @return self
     */
    public function setBillingPeriod($billingPeriod): self
    {
        $this->billingPeriod = $billingPeriod;

        return $this;
    }
    /**
     * @return string
     */
    public function getBillingPeriodUnit()
    {
        return $this->billingPeriodUnit;
    }

    /**
     * @param string $billingPeriodUnit
     *
     * @return self
     */
    public function setBillingPeriodUnit($billingPeriodUnit): self
    {
        $this->billingPeriodUnit = $billingPeriodUnit;

        return $this;
    }
    /**
     * @return string
     */
    public function getCurrencyCode()
    {
        return $this->currencyCode;
    }

    /**
     * @param string $currencyCode
     *
     * @return self
     */
    public function setCurrencyCode($currencyCode): self
    {
        $this->currencyCode = $currencyCode;

        return $this;
    }
    /**
     * @return int
     */
    public function getTotalPrice()
    {
        return $this->totalPrice;
    }

    /**
     * @param int $totalPrice
     *
     * @return self
     */
    public function setTotalPrice($totalPrice): self
    {
        $this->totalPrice = $totalPrice;

        return $this;
    }
    /**
     * @return int
     */
    public function getRenewalPrice()
    {
        return $this->renewalPrice;
    }

    /**
     * @param int $renewalPrice
     *
     * @return self
     */
    public function setRenewalPrice($renewalPrice): self
    {
        $this->renewalPrice = $renewalPrice;

        return $this;
    }
    /**
     * @return bool
     */
    public function getIsAutoRenewed()
    {
        return $this->isAutoRenewed;
    }

    /**
     * @param bool $isAutoRenewed
     *
     * @return self
     */
    public function setIsAutoRenewed($isAutoRenewed): self
    {
        $this->isAutoRenewed = $isAutoRenewed;

        return $this;
    }
    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     *
     * @return self
     */
    public function setCreatedAt($createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
    /**
     * @return \DateTime|null
     */
    public function getExpiresAt()
    {
        return $this->expiresAt;
    }

    /**
     * @param \DateTime|null $expiresAt
     *
     * @return self
     */
    public function setExpiresAt($expiresAt): self
    {
        $this->expiresAt = $expiresAt;

        return $this;
    }
    /**
     * @return \DateTime|null
     */
    public function getNextBillingAt()
    {
        return $this->nextBillingAt;
    }

    /**
     * @param \DateTime|null $nextBillingAt
     *
     * @return self
     */
    public function setNextBillingAt($nextBillingAt): self
    {
        $this->nextBillingAt = $nextBillingAt;

        return $this;
    }
}

