<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 0.0.96
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Hostinger\ObjectSerializer;

class BillingV1CatalogCatalogItemResource 
{
    /**
     * @var string $id
     */
    private $id;

    /**
     * @var string $name
     */
    private $name;

    /**
     * @var string $category
     */
    private $category;

    /**
     * @var object|null $metadata
     */
    private $metadata = null;

    /**
     * @var \Hostinger\Model\BillingV1CatalogCatalogItemPriceResource[] $prices
     */
    private $prices;

    /**
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param string $id
     */
    public function setId($id): self
    {
        $this->id = $id;

        return $this;
    }
    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName($name): self
    {
        $this->name = $name;

        return $this;
    }
    /**
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param string $category
     */
    public function setCategory($category): self
    {
        $this->category = $category;

        return $this;
    }
    /**
     * @return object|null
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * @param object|null $metadata
     */
    public function setMetadata($metadata): self
    {
        $this->metadata = $metadata;

        return $this;
    }
    /**
     * @return \Hostinger\Model\BillingV1CatalogCatalogItemPriceResource[]
     */
    public function getPrices()
    {
        return $this->prices;
    }

    /**
     * @param \Hostinger\Model\BillingV1CatalogCatalogItemPriceResource[] $prices
     */
    public function setPrices($prices): self
    {
        $this->prices = $prices;

        return $this;
    }
}

