<?php
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 0.0.96
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Hostinger\ObjectSerializer;

/**
 * @implements ArrayAccess<string, mixed>
 */
class BillingV1SubscriptionCancelRequest 
{
    /**
     * @param string|null $reasonCode
     * @param string|null $cancelOption
     */
    protected static $openAPIModelName = 'BillingV1SubscriptionCancelRequest';
    public function __construct(
        private $reasonCode = null,
        private $cancelOption = null,
    ) {
    }

    /**
     * @return string|null
     */
    public function getReasonCode()
    {
        return $this->reasonCode;
    }

    /**
     * @param string|null $reasonCode
     *
     * @return self
     */
    public function setReasonCode($reasonCode): self
    {
        $this->reasonCode = $reasonCode;

        return $this;
    }
    /**
     * @return string|null
     */
    public function getCancelOption()
    {
        return $this->cancelOption;
    }

    /**
     * @param string|null $cancelOption
     *
     * @return self
     */
    public function setCancelOption($cancelOption): self
    {
        $this->cancelOption = $cancelOption;

        return $this;
    }
}

