<?php
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 0.0.96
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Hostinger\ObjectSerializer;

/**
 * @implements ArrayAccess<string, mixed>
 */
class DNSV1ZoneUpdateRequest 
{
    /**
     * @param bool $overwrite
     * @param \Hostinger\Model\DNSV1ZoneUpdateRequestZoneInner[] $zone
     */
    protected static $openAPIModelName = 'DNSV1ZoneUpdateRequest';
    public function __construct(
        private $overwrite,
        private $zone,
    ) {
    }

    /**
     * @return bool
     */
    public function getOverwrite()
    {
        return $this->overwrite;
    }

    /**
     * @param bool $overwrite
     *
     * @return self
     */
    public function setOverwrite($overwrite): self
    {
        $this->overwrite = $overwrite;

        return $this;
    }
    /**
     * @return \Hostinger\Model\DNSV1ZoneUpdateRequestZoneInner[]
     */
    public function getZone()
    {
        return $this->zone;
    }

    /**
     * @param \Hostinger\Model\DNSV1ZoneUpdateRequestZoneInner[] $zone
     *
     * @return self
     */
    public function setZone($zone): self
    {
        $this->zone = $zone;

        return $this;
    }
}

