<?php
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 0.0.96
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Hostinger\ObjectSerializer;

/**
 * @implements ArrayAccess<string, mixed>
 */
class DNSV1ZoneDestroyRequest 
{
    /**
     * @param \Hostinger\Model\DNSV1ZoneDestroyRequestFiltersInner[] $filters
     */
    protected static $openAPIModelName = 'DNSV1ZoneDestroyRequest';
    public function __construct(
        private $filters,
    ) {
    }

    /**
     * @return \Hostinger\Model\DNSV1ZoneDestroyRequestFiltersInner[]
     */
    public function getFilters()
    {
        return $this->filters;
    }

    /**
     * @param \Hostinger\Model\DNSV1ZoneDestroyRequestFiltersInner[] $filters
     *
     * @return self
     */
    public function setFilters($filters): self
    {
        $this->filters = $filters;

        return $this;
    }
}

