<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 0.0.98
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class DomainsV1DomainDomainResource 
{
    public const string TYPE_DOMAIN = 'domain';
    public const string TYPE_FREE_DOMAIN = 'free_domain';
    public const string TYPE_DOMAIN_TRANSFER = 'domain_transfer';
    public const string TYPE_FREE_DOMAIN_TRANSFER = 'free_domain_transfer';

    public const string STATUS_ACTIVE = 'active';
    public const string STATUS_PENDING_SETUP = 'pending_setup';
    public const string STATUS_EXPIRED = 'expired';
    public const string STATUS_REQUESTED = 'requested';
    public const string STATUS_PENDING_VERIFICATION = 'pending_verification';
    public const string STATUS_DELETED = 'deleted';
    public const string STATUS_SUSPENDED = 'suspended';
    public const string STATUS_FAILED = 'failed';

    /**
     * @var int $id
     */
    private ?int $id;

    /**
     * @var string|null $domain
     */
    private ?string $domain = null;

    /**
     * @var string $type
     */
    private ?string $type;

    /**
     * @var string $status
     */
    private ?string $status;

    /**
     * @var \DateTime $createdAt
     */
    private ?\DateTime $createdAt;

    /**
     * @var \DateTime|null $expiresAt
     */
    private ?\DateTime $expiresAt = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @param int|null $id Domain ID
     */
    public function setId(?int $id): self
    {
        $this->id = $id;

        return $this;
    }
    public function getDomain(): ?string
    {
        return $this->domain;
    }

    /**
     * @param string|null $domain Domain name, `null` when not claimed free domain
     */
    public function setDomain(?string $domain): self
    {
        $this->domain = $domain;

        return $this;
    }
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * @param string|null $type type
     */
    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * @param string|null $status status
     */
    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime|null $createdAt createdAt
     */
    public function setCreatedAt(?\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
    public function getExpiresAt(): ?\DateTime
    {
        return $this->expiresAt;
    }

    /**
     * @param \DateTime|null $expiresAt expiresAt
     */
    public function setExpiresAt(?\DateTime $expiresAt): self
    {
        $this->expiresAt = $expiresAt;

        return $this;
    }
}

