<?php
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 0.0.96
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Hostinger\ObjectSerializer;

/**
 * @implements ArrayAccess<string, mixed>
 */
class DomainsV1PortfolioPurchaseRequest 
{
    /**
     * @param string $domain
     * @param string $itemId
     * @param int $paymentMethodId
     * @param \Hostinger\Model\DomainsV1PortfolioPurchaseRequestDomainContacts $domainContacts
     * @param object $additionalDetails
     * @param mixed[] $coupons
     */
    protected static $openAPIModelName = 'DomainsV1PortfolioPurchaseRequest';
    public function __construct(
        private $domain,
        private $itemId,
        private $paymentMethodId,
        private $domainContacts,
        private $additionalDetails,
        private $coupons,
    ) {
    }

    /**
     * @return string
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * @param string $domain
     *
     * @return self
     */
    public function setDomain($domain): self
    {
        $this->domain = $domain;

        return $this;
    }
    /**
     * @return string
     */
    public function getItemId()
    {
        return $this->itemId;
    }

    /**
     * @param string $itemId
     *
     * @return self
     */
    public function setItemId($itemId): self
    {
        $this->itemId = $itemId;

        return $this;
    }
    /**
     * @return int
     */
    public function getPaymentMethodId()
    {
        return $this->paymentMethodId;
    }

    /**
     * @param int $paymentMethodId
     *
     * @return self
     */
    public function setPaymentMethodId($paymentMethodId): self
    {
        $this->paymentMethodId = $paymentMethodId;

        return $this;
    }
    /**
     * @return \Hostinger\Model\DomainsV1PortfolioPurchaseRequestDomainContacts
     */
    public function getDomainContacts()
    {
        return $this->domainContacts;
    }

    /**
     * @param \Hostinger\Model\DomainsV1PortfolioPurchaseRequestDomainContacts $domainContacts
     *
     * @return self
     */
    public function setDomainContacts($domainContacts): self
    {
        $this->domainContacts = $domainContacts;

        return $this;
    }
    /**
     * @return object
     */
    public function getAdditionalDetails()
    {
        return $this->additionalDetails;
    }

    /**
     * @param object $additionalDetails
     *
     * @return self
     */
    public function setAdditionalDetails($additionalDetails): self
    {
        $this->additionalDetails = $additionalDetails;

        return $this;
    }
    /**
     * @return mixed[]
     */
    public function getCoupons()
    {
        return $this->coupons;
    }

    /**
     * @param mixed[] $coupons
     *
     * @return self
     */
    public function setCoupons($coupons): self
    {
        $this->coupons = $coupons;

        return $this;
    }
}

