<?php
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 0.0.96
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Hostinger\ObjectSerializer;

/**
 * @implements ArrayAccess<string, mixed>
 */
class DomainsV1PortfolioPurchaseRequestDomainContacts 
{
    /**
     * @param int $ownerId
     * @param int $adminId
     * @param int $billingId
     * @param int $techId
     */
    protected static $openAPIModelName = 'DomainsV1PortfolioPurchaseRequestDomainContacts';
    public function __construct(
        private $ownerId,
        private $adminId,
        private $billingId,
        private $techId,
    ) {
    }

    /**
     * @return int
     */
    public function getOwnerId()
    {
        return $this->ownerId;
    }

    /**
     * @param int $ownerId
     *
     * @return self
     */
    public function setOwnerId($ownerId): self
    {
        $this->ownerId = $ownerId;

        return $this;
    }
    /**
     * @return int
     */
    public function getAdminId()
    {
        return $this->adminId;
    }

    /**
     * @param int $adminId
     *
     * @return self
     */
    public function setAdminId($adminId): self
    {
        $this->adminId = $adminId;

        return $this;
    }
    /**
     * @return int
     */
    public function getBillingId()
    {
        return $this->billingId;
    }

    /**
     * @param int $billingId
     *
     * @return self
     */
    public function setBillingId($billingId): self
    {
        $this->billingId = $billingId;

        return $this;
    }
    /**
     * @return int
     */
    public function getTechId()
    {
        return $this->techId;
    }

    /**
     * @param int $techId
     *
     * @return self
     */
    public function setTechId($techId): self
    {
        $this->techId = $techId;

        return $this;
    }
}

