<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.18.2
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class EcommerceV1StoreStoreCreationResourceSalesChannel 
{
    /**
     * @var string
     */
    public const TYPE_BUILDER = 'builder';
    /**
     * @var string
     */
    public const TYPE_HORIZONS = 'horizons';
    /**
     * @var string
     */
    public const TYPE_TIKTOK = 'tiktok';
    /**
     * @var string
     */
    public const TYPE_CUSTOM = 'custom';
    /**
     * @var string
     */
    public const TYPE_QUICK_LINK = 'quick-link';
    /**
     * @var string
     */
    public const TYPE_WORDPRESS = 'wordpress';

    /**
     * @var string|null $id
     */
    private ?string $id;

    /**
     * @var string|null $type
     */
    private ?string $type;

    /**
     * @var string|null $externalId
     */
    private ?string $externalId = null;

    /**
    * @return string|null
    */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * @param string|null $id Sales channel ID
     */
    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * @param string|null $type Sales channel type
     */
    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getExternalId(): ?string
    {
        return $this->externalId;
    }

    /**
     * @param string|null $externalId External identifier for the sales channel
     */
    public function setExternalId(?string $externalId): self
    {
        $this->externalId = $externalId;

        return $this;
    }
}

