<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.42.4
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class EcommerceV1OrderOrderDetailResourceShippingAddress 
{

    /**
     * @var string|null $name
     */
    private ?string $name = null;

    /**
     * @var string|null $company
     */
    private ?string $company = null;

    /**
     * @var string|null $address1
     */
    private ?string $address1 = null;

    /**
     * @var string|null $address2
     */
    private ?string $address2 = null;

    /**
     * @var string|null $city
     */
    private ?string $city = null;

    /**
     * @var string|null $provinceCode
     */
    private ?string $provinceCode = null;

    /**
     * @var string|null $postalCode
     */
    private ?string $postalCode = null;

    /**
     * @var string|null $countryCode
     */
    private ?string $countryCode = null;

    /**
     * @var string|null $phone
     */
    private ?string $phone = null;

    /**
    * @return string|null
    */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string|null $name name
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getCompany(): ?string
    {
        return $this->company;
    }

    /**
     * @param string|null $company company
     */
    public function setCompany(?string $company): self
    {
        $this->company = $company;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getAddress1(): ?string
    {
        return $this->address1;
    }

    /**
     * @param string|null $address1 address1
     */
    public function setAddress1(?string $address1): self
    {
        $this->address1 = $address1;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getAddress2(): ?string
    {
        return $this->address2;
    }

    /**
     * @param string|null $address2 address2
     */
    public function setAddress2(?string $address2): self
    {
        $this->address2 = $address2;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /**
     * @param string|null $city city
     */
    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getProvinceCode(): ?string
    {
        return $this->provinceCode;
    }

    /**
     * @param string|null $provinceCode provinceCode
     */
    public function setProvinceCode(?string $provinceCode): self
    {
        $this->provinceCode = $provinceCode;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    /**
     * @param string|null $postalCode postalCode
     */
    public function setPostalCode(?string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getCountryCode(): ?string
    {
        return $this->countryCode;
    }

    /**
     * @param string|null $countryCode countryCode
     */
    public function setCountryCode(?string $countryCode): self
    {
        $this->countryCode = $countryCode;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getPhone(): ?string
    {
        return $this->phone;
    }

    /**
     * @param string|null $phone phone
     */
    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }
}

