<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.1.1
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class EcommerceV1SalesChannelSalesChannelCreationResourceSalesChannel 
{
    /**
     * @var string
     */
    public const TYPE_BUILDER = 'builder';
    /**
     * @var string
     */
    public const TYPE_HORIZONS = 'horizons';
    /**
     * @var string
     */
    public const TYPE_TIKTOK = 'tiktok';
    /**
     * @var string
     */
    public const TYPE_CUSTOM = 'custom';
    /**
     * @var string
     */
    public const TYPE_QUICK_LINK = 'quick-link';
    /**
     * @var string
     */
    public const TYPE_WORDPRESS = 'wordpress';

    /**
     * @var string|null $id
     */
    private ?string $id;

    /**
     * @var string|null $type
     */
    private ?string $type;

    /**
     * @var bool|null $isPrimary
     */
    private ?bool $isPrimary;

    /**
     * @var bool|null $isActive
     */
    private ?bool $isActive;

    /**
     * @var string|null $externalId
     */
    private ?string $externalId = null;

    /**
     * @var string|null $name
     */
    private ?string $name = null;

    /**
     * @var string|null $domain
     */
    private ?string $domain = null;

    /**
    * @return string|null
    */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * @param string|null $id Sales channel ID
     */
    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * @param string|null $type Sales channel type
     */
    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }
    /**
    * @return bool|null
    */
    public function getIsPrimary(): ?bool
    {
        return $this->isPrimary;
    }

    /**
     * @param bool|null $isPrimary Whether this is the primary sales channel.
     */
    public function setIsPrimary(?bool $isPrimary): self
    {
        $this->isPrimary = $isPrimary;

        return $this;
    }
    /**
    * @return bool|null
    */
    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    /**
     * @param bool|null $isActive Whether the sales channel is active.
     */
    public function setIsActive(?bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getExternalId(): ?string
    {
        return $this->externalId;
    }

    /**
     * @param string|null $externalId External identifier for the sales channel.
     */
    public function setExternalId(?string $externalId): self
    {
        $this->externalId = $externalId;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string|null $name Merchant-facing custom name.
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getDomain(): ?string
    {
        return $this->domain;
    }

    /**
     * @param string|null $domain Public address where the custom sales channel lives.
     */
    public function setDomain(?string $domain): self
    {
        $this->domain = $domain;

        return $this;
    }
}

