<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.42.4
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class EcommerceV1PaymentProviderPaymentProviderListResourceDataAvailableInner 
{

    /**
     * @var string|null $id
     */
    private ?string $id;

    /**
     * @var bool|null $isInstalled
     */
    private ?bool $isInstalled;

    /**
     * @var bool|null $isEnabled
     */
    private ?bool $isEnabled;

    /**
     * @var bool|null $isCurrencySupported
     */
    private ?bool $isCurrencySupported;

    /**
     * @var string[]|null $supportedCurrencies
     */
    private ?array $supportedCurrencies;

    /**
    * @return string|null
    */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * @param string|null $id The payment gateway ID, e.g. stripe.
     */
    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }
    /**
    * @return bool|null
    */
    public function getIsInstalled(): ?bool
    {
        return $this->isInstalled;
    }

    /**
     * @param bool|null $isInstalled Whether the gateway is installed on the store.
     */
    public function setIsInstalled(?bool $isInstalled): self
    {
        $this->isInstalled = $isInstalled;

        return $this;
    }
    /**
    * @return bool|null
    */
    public function getIsEnabled(): ?bool
    {
        return $this->isEnabled;
    }

    /**
     * @param bool|null $isEnabled Whether the gateway is enabled on the store.
     */
    public function setIsEnabled(?bool $isEnabled): self
    {
        $this->isEnabled = $isEnabled;

        return $this;
    }
    /**
    * @return bool|null
    */
    public function getIsCurrencySupported(): ?bool
    {
        return $this->isCurrencySupported;
    }

    /**
     * @param bool|null $isCurrencySupported Whether the gateway supports the store currency.
     */
    public function setIsCurrencySupported(?bool $isCurrencySupported): self
    {
        $this->isCurrencySupported = $isCurrencySupported;

        return $this;
    }
    /**
    * @return string[]|null
    */
    public function getSupportedCurrencies(): ?array
    {
        return $this->supportedCurrencies;
    }

    /**
     * @param string[]|null $supportedCurrencies Currencies the gateway supports; present only when the store currency is unsupported.
     */
    public function setSupportedCurrencies(?array $supportedCurrencies): self
    {
        $this->supportedCurrencies = $supportedCurrencies;

        return $this;
    }
}

