<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.62.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class HorizonsV1WebsitesWebsiteUrlResource 
{

    /**
     * @var string $websiteUrl
     */
    private string $websiteUrl;

    /**
     * @var \DateTime|null $publishedAt
     */
    private ?\DateTime $publishedAt = null;

    /**
     * @var bool|null $isTemplate
     */
    private ?bool $isTemplate;

    /**
     * @var bool|null $isInProgress
     */
    private ?bool $isInProgress;

    /**
     * @var bool|null $hasEcommerceStore
     */
    private ?bool $hasEcommerceStore;

    /**
    * @return string
    */
    public function getWebsiteUrl(): string
    {
        return $this->websiteUrl;
    }

    /**
     * @param string $websiteUrl The website URL for the user to access their website in Hostinger Horizons interface
     */
    public function setWebsiteUrl(string $websiteUrl): self
    {
        $this->websiteUrl = $websiteUrl;

        return $this;
    }
    /**
    * @return \DateTime|null
    */
    public function getPublishedAt(): ?\DateTime
    {
        return $this->publishedAt;
    }

    /**
     * @param \DateTime|null $publishedAt When the website was last published, or null if it has never been published
     */
    public function setPublishedAt(?\DateTime $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }
    /**
    * @return bool|null
    */
    public function getIsTemplate(): ?bool
    {
        return $this->isTemplate;
    }

    /**
     * @param bool|null $isTemplate Whether the website is published as a template, so its published pages show a \"Use template\" banner
     */
    public function setIsTemplate(?bool $isTemplate): self
    {
        $this->isTemplate = $isTemplate;

        return $this;
    }
    /**
    * @return bool|null
    */
    public function getIsInProgress(): ?bool
    {
        return $this->isInProgress;
    }

    /**
     * @param bool|null $isInProgress Whether Hostinger Horizons is still generating changes or publishing the website. Publishing is refused while it is true, and editing while changes are being generated. An unfinished template migration also refuses publishing, with its own error, without setting this flag.
     */
    public function setIsInProgress(?bool $isInProgress): self
    {
        $this->isInProgress = $isInProgress;

        return $this;
    }
    /**
    * @return bool|null
    */
    public function getHasEcommerceStore(): ?bool
    {
        return $this->hasEcommerceStore;
    }

    /**
     * @param bool|null $hasEcommerceStore Whether the website has an ecommerce store
     */
    public function setHasEcommerceStore(?bool $hasEcommerceStore): self
    {
        $this->hasEcommerceStore = $hasEcommerceStore;

        return $this;
    }
}

