<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.54.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class HostingV1NodeJsStartBuildRequestSourceOptions 
{

    /**
     * @var string|null $archivePath
     */
    private ?string $archivePath;

    /**
     * @var string|null $owner
     */
    private ?string $owner;

    /**
     * @var string|null $repository
     */
    private ?string $repository;

    /**
     * @var string|null $branch
     */
    private ?string $branch;

    /**
     * @var string|null $installationUuid
     */
    private ?string $installationUuid;

    /**
    * @return string|null
    */
    public function getArchivePath(): ?string
    {
        return $this->archivePath;
    }

    /**
     * @param string|null $archivePath The path to the archive file relative to the document root of the vhost (required if source is \"archive\")
     */
    public function setArchivePath(?string $archivePath): self
    {
        $this->archivePath = $archivePath;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getOwner(): ?string
    {
        return $this->owner;
    }

    /**
     * @param string|null $owner Repository owner login (required if source is \"git\"). GitLab group paths use slashes.
     */
    public function setOwner(?string $owner): self
    {
        $this->owner = $owner;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getRepository(): ?string
    {
        return $this->repository;
    }

    /**
     * @param string|null $repository Repository name without the .git suffix (required if source is \"git\")
     */
    public function setRepository(?string $repository): self
    {
        $this->repository = $repository;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getBranch(): ?string
    {
        return $this->branch;
    }

    /**
     * @param string|null $branch Branch to build (required if source is \"git\")
     */
    public function setBranch(?string $branch): self
    {
        $this->branch = $branch;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getInstallationUuid(): ?string
    {
        return $this->installationUuid;
    }

    /**
     * @param string|null $installationUuid Git installation used to access the repository (required if source is \"git\")
     */
    public function setInstallationUuid(?string $installationUuid): self
    {
        $this->installationUuid = $installationUuid;

        return $this;
    }
}

