<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.5.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class HostingV1DatabasesCreateDatabaseRequest 
{

    /**
     * @var string $name
     */
    private string $name;

    /**
     * @var string $user
     */
    private string $user;

    /**
     * @var string $password
     */
    private string $password;

    /**
     * @var string $websiteDomain
     */
    private string $websiteDomain;

    /**
    * @return string
    */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name Database name. If the account username prefix is omitted, it is added automatically.
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
    /**
    * @return string
    */
    public function getUser(): string
    {
        return $this->user;
    }

    /**
     * @param string $user Database user. If the account username prefix is omitted, it is added automatically.
     */
    public function setUser(string $user): self
    {
        $this->user = $user;

        return $this;
    }
    /**
    * @return string
    */
    public function getPassword(): string
    {
        return $this->password;
    }

    /**
     * @param string $password Database user password.
     */
    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }
    /**
    * @return string
    */
    public function getWebsiteDomain(): string
    {
        return $this->websiteDomain;
    }

    /**
     * @param string $websiteDomain Website domain assigned to the database.
     */
    public function setWebsiteDomain(string $websiteDomain): self
    {
        $this->websiteDomain = $websiteDomain;

        return $this;
    }
}

