<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.38.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class HostingV1RedirectsCreateRedirectRequest 
{

    /**
     * @var string $from
     */
    private string $from;

    /**
     * @var string $to
     */
    private string $to;

    /**
    * @return string
    */
    public function getFrom(): string
    {
        return $this->from;
    }

    /**
     * @param string $from Source URL on the selected website
     */
    public function setFrom(string $from): self
    {
        $this->from = $from;

        return $this;
    }
    /**
    * @return string
    */
    public function getTo(): string
    {
        return $this->to;
    }

    /**
     * @param string $to Destination URL or IP address
     */
    public function setTo(string $to): self
    {
        $this->to = $to;

        return $this;
    }
}

