<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.2.1
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class HostingV1CronJobsCreateCronJobRequest 
{

    /**
     * @var string $time
     */
    private string $time;

    /**
     * @var string $command
     */
    private string $command;

    /**
    * @return string
    */
    public function getTime(): string
    {
        return $this->time;
    }

    /**
     * @param string $time Cron schedule expression (for example \"0 2 * * *\" runs daily at 02:00).
     */
    public function setTime(string $time): self
    {
        $this->time = $time;

        return $this;
    }
    /**
    * @return string
    */
    public function getCommand(): string
    {
        return $this->command;
    }

    /**
     * @param string $command Command to execute on the schedule.
     */
    public function setCommand(string $command): self
    {
        $this->command = $command;

        return $this;
    }
}

