<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.62.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class HostingV1OnboardingsStartOnboardingRequest 
{
    /**
     * @var string
     */
    public const TYPE_WORDPRESS = 'wordpress';
    /**
     * @var string
     */
    public const TYPE_HEADLESS_WORDPRESS = 'headless_wordpress';
    /**
     * @var string
     */
    public const TYPE_HEADLESS_ECOMMERCE = 'headless_ecommerce';
    /**
     * @var string
     */
    public const TYPE_HEADLESS_POCKETBASE = 'headless_pocketbase';

    /**
     * @var string|null $type
     */
    private ?string $type = null;

    /**
     * @var string|null $domain
     */
    private ?string $domain = null;

    /**
     * @var \Hostinger\Model\HostingV1OnboardingsStartOnboardingRequestWordpress|null $wordpress
     */
    private ?\Hostinger\Model\HostingV1OnboardingsStartOnboardingRequestWordpress $wordpress = null;

    /**
    * @return string|null
    */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * @param string|null $type Website type. Omit or `null` for an empty website. `wordpress` installs WordPress in the website root and requires `wordpress`. The headless types (`headless_wordpress`, `headless_ecommerce`, `headless_pocketbase`) create a headless website; `headless_wordpress` additionally installs WordPress into the `cms` directory with generated credentials.
     */
    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getDomain(): ?string
    {
        return $this->domain;
    }

    /**
     * @param string|null $domain Customer-owned domain. Cannot start with \"www.\". Omit or `null` to set the website up on a generated temporary free subdomain.
     */
    public function setDomain(?string $domain): self
    {
        $this->domain = $domain;

        return $this;
    }
    /**
    * @return \Hostinger\Model\HostingV1OnboardingsStartOnboardingRequestWordpress|null
    */
    public function getWordpress(): ?\Hostinger\Model\HostingV1OnboardingsStartOnboardingRequestWordpress
    {
        return $this->wordpress;
    }

    /**
     * @param \Hostinger\Model\HostingV1OnboardingsStartOnboardingRequestWordpress|null $wordpress wordpress
     */
    public function setWordpress(?\Hostinger\Model\HostingV1OnboardingsStartOnboardingRequestWordpress $wordpress): self
    {
        $this->wordpress = $wordpress;

        return $this;
    }
}

