<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.14.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class HostingV1NodeJsCreateFromArchiveRequest 
{
    /**
     * @var int
     */
    public const NODE_VERSION_NUMBER_18 = 18;
    /**
     * @var int
     */
    public const NODE_VERSION_NUMBER_20 = 20;
    /**
     * @var int
     */
    public const NODE_VERSION_NUMBER_22 = 22;
    /**
     * @var int
     */
    public const NODE_VERSION_NUMBER_24 = 24;

    /**
     * @var string
     */
    public const APP_TYPE_CREATE_REACT_APP = 'create-react-app';
    /**
     * @var string
     */
    public const APP_TYPE_VITE = 'vite';
    /**
     * @var string
     */
    public const APP_TYPE_ANGULAR = 'angular';
    /**
     * @var string
     */
    public const APP_TYPE_REACT = 'react';
    /**
     * @var string
     */
    public const APP_TYPE_VUE = 'vue';
    /**
     * @var string
     */
    public const APP_TYPE_PARCEL = 'parcel';
    /**
     * @var string
     */
    public const APP_TYPE_EXPRESS = 'express';
    /**
     * @var string
     */
    public const APP_TYPE_FASTIFY = 'fastify';
    /**
     * @var string
     */
    public const APP_TYPE_NEST = 'nest';

    /**
     * @var string
     */
    public const PACKAGE_MANAGER_NPM = 'npm';
    /**
     * @var string
     */
    public const PACKAGE_MANAGER_YARN = 'yarn';
    /**
     * @var string
     */
    public const PACKAGE_MANAGER_PNPM = 'pnpm';

    /**
     * @var string $archive
     */
    private string $archive;

    /**
     * @var int|null $nodeVersion
     */
    private ?int $nodeVersion = null;

    /**
     * @var string|null $appType
     */
    private ?string $appType = null;

    /**
     * @var string|null $rootDirectory
     */
    private ?string $rootDirectory = null;

    /**
     * @var string|null $outputDirectory
     */
    private ?string $outputDirectory = null;

    /**
     * @var string|null $buildScript
     */
    private ?string $buildScript = null;

    /**
     * @var string|null $entryFile
     */
    private ?string $entryFile = null;

    /**
     * @var string|null $packageManager
     */
    private ?string $packageManager = null;

    /**
    * @return string
    */
    public function getArchive(): string
    {
        return $this->archive;
    }

    /**
     * @param string $archive Project archive file (.zip, .tar.gz, or .tgz), maximum 50MB
     */
    public function setArchive(string $archive): self
    {
        $this->archive = $archive;

        return $this;
    }
    /**
    * @return int|null
    */
    public function getNodeVersion(): ?int
    {
        return $this->nodeVersion;
    }

    /**
     * @param int|null $nodeVersion Node.js version override (auto-detected from package.json if omitted)
     */
    public function setNodeVersion(?int $nodeVersion): self
    {
        $this->nodeVersion = $nodeVersion;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getAppType(): ?string
    {
        return $this->appType;
    }

    /**
     * @param string|null $appType Node.js application type override
     */
    public function setAppType(?string $appType): self
    {
        $this->appType = $appType;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getRootDirectory(): ?string
    {
        return $this->rootDirectory;
    }

    /**
     * @param string|null $rootDirectory Application root directory override (where package.json is located) relative to public_html
     */
    public function setRootDirectory(?string $rootDirectory): self
    {
        $this->rootDirectory = $rootDirectory;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getOutputDirectory(): ?string
    {
        return $this->outputDirectory;
    }

    /**
     * @param string|null $outputDirectory Build output directory override relative to the root directory
     */
    public function setOutputDirectory(?string $outputDirectory): self
    {
        $this->outputDirectory = $outputDirectory;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getBuildScript(): ?string
    {
        return $this->buildScript;
    }

    /**
     * @param string|null $buildScript Build script override
     */
    public function setBuildScript(?string $buildScript): self
    {
        $this->buildScript = $buildScript;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getEntryFile(): ?string
    {
        return $this->entryFile;
    }

    /**
     * @param string|null $entryFile Main entry point file override
     */
    public function setEntryFile(?string $entryFile): self
    {
        $this->entryFile = $entryFile;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getPackageManager(): ?string
    {
        return $this->packageManager;
    }

    /**
     * @param string|null $packageManager Package manager override
     */
    public function setPackageManager(?string $packageManager): self
    {
        $this->packageManager = $packageManager;

        return $this;
    }
}

