<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.14.1
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class HostingV1PhpUpdatePhpExtensionsRequest 
{

    /**
     * @var string[]|null $enable
     */
    private ?array $enable;

    /**
     * @var string[]|null $disable
     */
    private ?array $disable;

    /**
    * @return string[]|null
    */
    public function getEnable(): ?array
    {
        return $this->enable;
    }

    /**
     * @param string[]|null $enable PHP extensions to enable.
     */
    public function setEnable(?array $enable): self
    {
        $this->enable = $enable;

        return $this;
    }
    /**
    * @return string[]|null
    */
    public function getDisable(): ?array
    {
        return $this->disable;
    }

    /**
     * @param string[]|null $disable PHP extensions to disable.
     */
    public function setDisable(?array $disable): self
    {
        $this->disable = $disable;

        return $this;
    }
}

