<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 0.21.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class HostingV1DomainsSubdomainResource 
{

    /**
     * @var string|null $username
     */
    private ?string $username;

    /**
     * @var string|null $domain
     */
    private ?string $domain;

    /**
     * @var string|null $parentDomain
     */
    private ?string $parentDomain;

    /**
     * @var string|null $rootDirectory
     */
    private ?string $rootDirectory;

    /**
     * @var string|null $subdomain
     */
    private ?string $subdomain;

    /**
    * @return string|null
    */
    public function getUsername(): ?string
    {
        return $this->username;
    }

    /**
     * @param string|null $username Website username
     */
    public function setUsername(?string $username): self
    {
        $this->username = $username;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getDomain(): ?string
    {
        return $this->domain;
    }

    /**
     * @param string|null $domain Full subdomain
     */
    public function setDomain(?string $domain): self
    {
        $this->domain = $domain;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getParentDomain(): ?string
    {
        return $this->parentDomain;
    }

    /**
     * @param string|null $parentDomain Parent website domain
     */
    public function setParentDomain(?string $parentDomain): self
    {
        $this->parentDomain = $parentDomain;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getRootDirectory(): ?string
    {
        return $this->rootDirectory;
    }

    /**
     * @param string|null $rootDirectory Subdomain root directory
     */
    public function setRootDirectory(?string $rootDirectory): self
    {
        $this->rootDirectory = $rootDirectory;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getSubdomain(): ?string
    {
        return $this->subdomain;
    }

    /**
     * @param string|null $subdomain Subdomain prefix
     */
    public function setSubdomain(?string $subdomain): self
    {
        $this->subdomain = $subdomain;

        return $this;
    }
}

