<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.53.1
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class HostingV1GitGitInstallationResource 
{
    /**
     * @var string
     */
    public const PROVIDER_GITHUB = 'github';
    /**
     * @var string
     */
    public const PROVIDER_GITLAB = 'gitlab';
    /**
     * @var string
     */
    public const PROVIDER_BITBUCKET = 'bitbucket';

    /**
     * @var string
     */
    public const ACCOUNT_TYPE_USER = 'User';
    /**
     * @var string
     */
    public const ACCOUNT_TYPE_ORGANIZATION = 'Organization';

    /**
     * @var string
     */
    public const STATUS_PENDING = 'pending';
    /**
     * @var string
     */
    public const STATUS_ACTIVE = 'active';
    /**
     * @var string
     */
    public const STATUS_SUSPENDED = 'suspended';

    /**
     * @var string $uuid
     */
    private string $uuid;

    /**
     * @var string $provider
     */
    private string $provider;

    /**
     * @var string $accountLogin
     */
    private ?string $accountLogin = null;

    /**
     * @var string $accountType
     */
    private ?string $accountType = null;

    /**
     * @var string $accountAvatarUrl
     */
    private ?string $accountAvatarUrl = null;

    /**
     * @var string $status
     */
    private string $status;

    /**
     * @var \DateTime $installedAt
     */
    private ?\DateTime $installedAt = null;

    /**
     * @var \DateTime $createdAt
     */
    private \DateTime $createdAt;

    /**
     * @var bool $hasOauth
     */
    private ?bool $hasOauth = null;

    /**
    * @return string
    */
    public function getUuid(): string
    {
        return $this->uuid;
    }

    /**
     * @param string $uuid Installation identifier. Use it as the path parameter of List Git installation repositories.
     */
    public function setUuid(string $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }
    /**
    * @return string
    */
    public function getProvider(): string
    {
        return $this->provider;
    }

    /**
     * @param string $provider Git provider the account belongs to
     */
    public function setProvider(string $provider): self
    {
        $this->provider = $provider;

        return $this;
    }
    /**
    * @return string
    */
    public function getAccountLogin(): ?string
    {
        return $this->accountLogin;
    }

    /**
     * @param string $accountLogin Login of the connected provider account (user or organization)
     */
    public function setAccountLogin(?string $accountLogin): self
    {
        $this->accountLogin = $accountLogin;

        return $this;
    }
    /**
    * @return string
    */
    public function getAccountType(): ?string
    {
        return $this->accountType;
    }

    /**
     * @param string $accountType Whether the connected account is a user or an organization
     */
    public function setAccountType(?string $accountType): self
    {
        $this->accountType = $accountType;

        return $this;
    }
    /**
    * @return string
    */
    public function getAccountAvatarUrl(): ?string
    {
        return $this->accountAvatarUrl;
    }

    /**
     * @param string $accountAvatarUrl Avatar URL of the connected provider account
     */
    public function setAccountAvatarUrl(?string $accountAvatarUrl): self
    {
        $this->accountAvatarUrl = $accountAvatarUrl;

        return $this;
    }
    /**
    * @return string
    */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * @param string $status Installation status. Only active installations are listed unless the status filter says otherwise.
     */
    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }
    /**
    * @return \DateTime
    */
    public function getInstalledAt(): ?\DateTime
    {
        return $this->installedAt;
    }

    /**
     * @param \DateTime $installedAt When the provider app was installed on the account
     */
    public function setInstalledAt(?\DateTime $installedAt): self
    {
        $this->installedAt = $installedAt;

        return $this;
    }
    /**
    * @return \DateTime
    */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt When the installation record was created
     */
    public function setCreatedAt(\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
    /**
    * @return bool
    */
    public function getHasOauth(): ?bool
    {
        return $this->hasOauth;
    }

    /**
     * @param bool $hasOauth True when the GitHub user account has a stored OAuth token whose refresh token is still valid, false when the token is missing or its refresh token expired. Null for organization accounts and for providers other than GitHub.
     */
    public function setHasOauth(?bool $hasOauth): self
    {
        $this->hasOauth = $hasOauth;

        return $this;
    }
}

