<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.20.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class MailV1SchemaCreateApiTokenRequestSchema 
{

    /**
     * @var string $name
     */
    private string $name;

    /**
     * @var \Hostinger\Model\MailV1SchemaCreateApiTokenRequestSchemaScope $scope
     */
    private \Hostinger\Model\MailV1SchemaCreateApiTokenRequestSchemaScope $scope;

    /**
    * @return string
    */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name Human-readable label for this token
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
    /**
    * @return \Hostinger\Model\MailV1SchemaCreateApiTokenRequestSchemaScope
    */
    public function getScope(): \Hostinger\Model\MailV1SchemaCreateApiTokenRequestSchemaScope
    {
        return $this->scope;
    }

    /**
     * @param \Hostinger\Model\MailV1SchemaCreateApiTokenRequestSchemaScope $scope scope
     */
    public function setScope(\Hostinger\Model\MailV1SchemaCreateApiTokenRequestSchemaScope $scope): self
    {
        $this->scope = $scope;

        return $this;
    }
}

