<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.20.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class MailV1LogsMailboxActionsMailboxActionLogResource 
{
    /**
     * @var string
     */
    public const EVENT_MESSAGE_NEW = 'MessageNew';
    /**
     * @var string
     */
    public const EVENT_MESSAGE_READ = 'MessageRead';
    /**
     * @var string
     */
    public const EVENT_MESSAGE_APPEND = 'MessageAppend';
    /**
     * @var string
     */
    public const EVENT_MESSAGE_EXPUNGE = 'MessageExpunge';
    /**
     * @var string
     */
    public const EVENT_MAILBOX_CREATE = 'MailboxCreate';
    /**
     * @var string
     */
    public const EVENT_MAILBOX_DELETE = 'MailboxDelete';
    /**
     * @var string
     */
    public const EVENT_MAILBOX_RENAME = 'MailboxRename';

    /**
     * @var string|null $folder
     */
    private ?string $folder;

    /**
     * @var int|null $time
     */
    private ?int $time;

    /**
     * @var string|null $event
     */
    private ?string $event;

    /**
     * @var string|null $mailbox
     */
    private ?string $mailbox;

    /**
     * @var string|null $hostname
     */
    private ?string $hostname;

    /**
     * @var \DateTime|null $timestamp
     */
    private ?\DateTime $timestamp;

    /**
    * @return string|null
    */
    public function getFolder(): ?string
    {
        return $this->folder;
    }

    /**
     * @param string|null $folder folder
     */
    public function setFolder(?string $folder): self
    {
        $this->folder = $folder;

        return $this;
    }
    /**
    * @return int|null
    */
    public function getTime(): ?int
    {
        return $this->time;
    }

    /**
     * @param int|null $time Unix timestamp of the event
     */
    public function setTime(?int $time): self
    {
        $this->time = $time;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getEvent(): ?string
    {
        return $this->event;
    }

    /**
     * @param string|null $event event
     */
    public function setEvent(?string $event): self
    {
        $this->event = $event;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getMailbox(): ?string
    {
        return $this->mailbox;
    }

    /**
     * @param string|null $mailbox Mailbox email address
     */
    public function setMailbox(?string $mailbox): self
    {
        $this->mailbox = $mailbox;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getHostname(): ?string
    {
        return $this->hostname;
    }

    /**
     * @param string|null $hostname hostname
     */
    public function setHostname(?string $hostname): self
    {
        $this->hostname = $hostname;

        return $this;
    }
    /**
    * @return \DateTime|null
    */
    public function getTimestamp(): ?\DateTime
    {
        return $this->timestamp;
    }

    /**
     * @param \DateTime|null $timestamp timestamp
     */
    public function setTimestamp(?\DateTime $timestamp): self
    {
        $this->timestamp = $timestamp;

        return $this;
    }
}

