<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.15.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class MailV1LogsCommonDeliveryLogRelayEventResource 
{

    /**
     * @var string|null $addressTo
     */
    private ?string $addressTo;

    /**
     * @var string|null $relay
     */
    private ?string $relay;

    /**
     * @var string|null $delay
     */
    private ?string $delay;

    /**
     * @var string|null $dsn
     */
    private ?string $dsn;

    /**
     * @var string|null $status
     */
    private ?string $status;

    /**
     * @var string|null $response
     */
    private ?string $response;

    /**
     * @var \DateTime|null $time
     */
    private ?\DateTime $time;

    /**
    * @return string|null
    */
    public function getAddressTo(): ?string
    {
        return $this->addressTo;
    }

    /**
     * @param string|null $addressTo addressTo
     */
    public function setAddressTo(?string $addressTo): self
    {
        $this->addressTo = $addressTo;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getRelay(): ?string
    {
        return $this->relay;
    }

    /**
     * @param string|null $relay relay
     */
    public function setRelay(?string $relay): self
    {
        $this->relay = $relay;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getDelay(): ?string
    {
        return $this->delay;
    }

    /**
     * @param string|null $delay delay
     */
    public function setDelay(?string $delay): self
    {
        $this->delay = $delay;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getDsn(): ?string
    {
        return $this->dsn;
    }

    /**
     * @param string|null $dsn dsn
     */
    public function setDsn(?string $dsn): self
    {
        $this->dsn = $dsn;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * @param string|null $status status
     */
    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getResponse(): ?string
    {
        return $this->response;
    }

    /**
     * @param string|null $response response
     */
    public function setResponse(?string $response): self
    {
        $this->response = $response;

        return $this;
    }
    /**
    * @return \DateTime|null
    */
    public function getTime(): ?\DateTime
    {
        return $this->time;
    }

    /**
     * @param \DateTime|null $time time
     */
    public function setTime(?\DateTime $time): self
    {
        $this->time = $time;

        return $this;
    }
}

