<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.35.1
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class MailV1AliasesAliasResource 
{

    /**
     * @var string|null $id
     */
    private ?string $id;

    /**
     * @var string|null $address
     */
    private ?string $address;

    /**
     * @var \Hostinger\Model\MailV1AliasesAliasMailboxResource|null $mailbox
     */
    private ?\Hostinger\Model\MailV1AliasesAliasMailboxResource $mailbox;

    /**
     * @var bool|null $isActive
     */
    private ?bool $isActive;

    /**
     * @var \DateTime|null $createdAt
     */
    private ?\DateTime $createdAt = null;

    /**
     * @var \DateTime|null $updatedAt
     */
    private ?\DateTime $updatedAt;

    /**
    * @return string|null
    */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * @param string|null $id Unique alias identifier
     */
    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getAddress(): ?string
    {
        return $this->address;
    }

    /**
     * @param string|null $address Email address of the alias
     */
    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }
    /**
    * @return \Hostinger\Model\MailV1AliasesAliasMailboxResource|null
    */
    public function getMailbox(): ?\Hostinger\Model\MailV1AliasesAliasMailboxResource
    {
        return $this->mailbox;
    }

    /**
     * @param \Hostinger\Model\MailV1AliasesAliasMailboxResource|null $mailbox mailbox
     */
    public function setMailbox(?\Hostinger\Model\MailV1AliasesAliasMailboxResource $mailbox): self
    {
        $this->mailbox = $mailbox;

        return $this;
    }
    /**
    * @return bool|null
    */
    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    /**
     * @param bool|null $isActive Whether the alias is active and not suspended
     */
    public function setIsActive(?bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }
    /**
    * @return \DateTime|null
    */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime|null $createdAt createdAt
     */
    public function setCreatedAt(?\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
    /**
    * @return \DateTime|null
    */
    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime|null $updatedAt updatedAt
     */
    public function setUpdatedAt(?\DateTime $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

