<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.18.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class MailV1LogsActionActionLogResource 
{
    /**
     * @var string
     */
    public const RESPONSE_STATUS_OK = 'OK';
    /**
     * @var string
     */
    public const RESPONSE_STATUS_FAIL = 'Fail';

    /**
     * @var string|null $action
     */
    private ?string $action;

    /**
     * @var object|null $extra
     */
    private ?object $extra = null;

    /**
     * @var \DateTime|null $createdAt
     */
    private ?\DateTime $createdAt;

    /**
     * @var string|null $ipAddress
     */
    private ?string $ipAddress;

    /**
     * @var string|null $role
     */
    private ?string $role;

    /**
     * @var string|null $actionContext
     */
    private ?string $actionContext;

    /**
     * @var string|null $responseStatus
     */
    private ?string $responseStatus;

    /**
    * @return string|null
    */
    public function getAction(): ?string
    {
        return $this->action;
    }

    /**
     * @param string|null $action action
     */
    public function setAction(?string $action): self
    {
        $this->action = $action;

        return $this;
    }
    /**
    * @return object|null
    */
    public function getExtra(): ?object
    {
        return $this->extra;
    }

    /**
     * @param object|null $extra Arbitrary contextual payload
     */
    public function setExtra(?object $extra): self
    {
        $this->extra = $extra;

        return $this;
    }
    /**
    * @return \DateTime|null
    */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime|null $createdAt createdAt
     */
    public function setCreatedAt(?\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getIpAddress(): ?string
    {
        return $this->ipAddress;
    }

    /**
     * @param string|null $ipAddress Only populated for user-role logs
     */
    public function setIpAddress(?string $ipAddress): self
    {
        $this->ipAddress = $ipAddress;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getRole(): ?string
    {
        return $this->role;
    }

    /**
     * @param string|null $role role
     */
    public function setRole(?string $role): self
    {
        $this->role = $role;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getActionContext(): ?string
    {
        return $this->actionContext;
    }

    /**
     * @param string|null $actionContext actionContext
     */
    public function setActionContext(?string $actionContext): self
    {
        $this->actionContext = $actionContext;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getResponseStatus(): ?string
    {
        return $this->responseStatus;
    }

    /**
     * @param string|null $responseStatus responseStatus
     */
    public function setResponseStatus(?string $responseStatus): self
    {
        $this->responseStatus = $responseStatus;

        return $this;
    }
}

