<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.18.1
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class MailV1ApiTokensApiTokenScopeResource 
{

    /**
     * @var bool|null $hasAllMailboxes
     */
    private ?bool $hasAllMailboxes;

    /**
     * @var \Hostinger\Model\MailV1ApiTokensApiTokenMailboxResource[]|null $mailboxes
     */
    private ?array $mailboxes;

    /**
    * @return bool|null
    */
    public function getHasAllMailboxes(): ?bool
    {
        return $this->hasAllMailboxes;
    }

    /**
     * @param bool|null $hasAllMailboxes Whether the token covers all current and future mailboxes of the order
     */
    public function setHasAllMailboxes(?bool $hasAllMailboxes): self
    {
        $this->hasAllMailboxes = $hasAllMailboxes;

        return $this;
    }
    /**
    * @return \Hostinger\Model\MailV1ApiTokensApiTokenMailboxResource[]|null
    */
    public function getMailboxes(): ?array
    {
        return $this->mailboxes;
    }

    /**
     * @param \Hostinger\Model\MailV1ApiTokensApiTokenMailboxResource[]|null $mailboxes Mailboxes this token grants access to. Empty when `has_all_mailboxes` is true.
     */
    public function setMailboxes(?array $mailboxes): self
    {
        $this->mailboxes = $mailboxes;

        return $this;
    }
}

