<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.18.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class MailV1SchemaCreateApiTokenRequestSchemaScope 
{

    /**
     * @var bool $hasAllMailboxes
     */
    private bool $hasAllMailboxes;

    /**
     * @var string[]|null $mailboxIds
     */
    private ?array $mailboxIds;

    /**
    * @return bool
    */
    public function getHasAllMailboxes(): bool
    {
        return $this->hasAllMailboxes;
    }

    /**
     * @param bool $hasAllMailboxes Grant access to all current and future mailboxes of the order
     */
    public function setHasAllMailboxes(bool $hasAllMailboxes): self
    {
        $this->hasAllMailboxes = $hasAllMailboxes;

        return $this;
    }
    /**
    * @return string[]|null
    */
    public function getMailboxIds(): ?array
    {
        return $this->mailboxIds;
    }

    /**
     * @param string[]|null $mailboxIds Required when `has_all_mailboxes` is false. Mailbox resource IDs of this order.
     */
    public function setMailboxIds(?array $mailboxIds): self
    {
        $this->mailboxIds = $mailboxIds;

        return $this;
    }
}

