<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.42.3
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class ReachListAutomationsV1200Response 
{

    /**
     * @var \Hostinger\Model\ReachV1AutomationsAutomationResource[]|null $data
     */
    private ?array $data;

    /**
     * @var \Hostinger\Model\CommonSchemaPaginationMetaSchema|null $meta
     */
    private ?\Hostinger\Model\CommonSchemaPaginationMetaSchema $meta;

    /**
    * @return \Hostinger\Model\ReachV1AutomationsAutomationResource[]|null
    */
    public function getData(): ?array
    {
        return $this->data;
    }

    /**
     * @param \Hostinger\Model\ReachV1AutomationsAutomationResource[]|null $data Array of [`Reach.V1.Automations.AutomationResource`](#model/reachv1automationsautomationresource)
     */
    public function setData(?array $data): self
    {
        $this->data = $data;

        return $this;
    }
    /**
    * @return \Hostinger\Model\CommonSchemaPaginationMetaSchema|null
    */
    public function getMeta(): ?\Hostinger\Model\CommonSchemaPaginationMetaSchema
    {
        return $this->meta;
    }

    /**
     * @param \Hostinger\Model\CommonSchemaPaginationMetaSchema|null $meta meta
     */
    public function setMeta(?\Hostinger\Model\CommonSchemaPaginationMetaSchema $meta): self
    {
        $this->meta = $meta;

        return $this;
    }
}

