<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.35.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class ReachV1ContactsFieldsUpdateRequest 
{

    /**
     * @var string $label
     */
    private string $label;

    /**
     * @var \Hostinger\Model\ReachV1ContactsFieldsUpdateRequestOptionsInner[]|null $options
     */
    private ?array $options = null;

    /**
    * @return string
    */
    public function getLabel(): string
    {
        return $this->label;
    }

    /**
     * @param string $label label
     */
    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }
    /**
    * @return \Hostinger\Model\ReachV1ContactsFieldsUpdateRequestOptionsInner[]|null
    */
    public function getOptions(): ?array
    {
        return $this->options;
    }

    /**
     * @param \Hostinger\Model\ReachV1ContactsFieldsUpdateRequestOptionsInner[]|null $options Replaces the option set when provided. Entries carrying a uuid are kept and relabelled, entries without one are created, and any existing option missing from the list is deleted along with the values contacts hold for it.
     */
    public function setOptions(?array $options): self
    {
        $this->options = $options;

        return $this;
    }
}

