<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.43.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class ReachV1ContactsSegmentsProfileFilterContactsRequest 
{
    /**
     * @var string
     */
    public const LOGIC__AND = 'AND';
    /**
     * @var string
     */
    public const LOGIC__OR = 'OR';

    /**
     * @var string
     */
    public const SORT_BY_EMAIL = 'email';
    /**
     * @var string
     */
    public const SORT_BY_NAME = 'name';
    /**
     * @var string
     */
    public const SORT_BY_SURNAME = 'surname';
    /**
     * @var string
     */
    public const SORT_BY_PHONE = 'phone';
    /**
     * @var string
     */
    public const SORT_BY_SUBSCRIPTION_STATUS = 'subscription_status';

    /**
     * @var string
     */
    public const SORT_DIRECTION_ASC = 'asc';
    /**
     * @var string
     */
    public const SORT_DIRECTION_DESC = 'desc';

    /**
     * @var \Hostinger\Model\ReachV1ContactsSegmentsProfileFilterContactsRequestConditionsInner[] $conditions
     */
    private array $conditions;

    /**
     * @var string $logic
     */
    private string $logic;

    /**
     * @var int|null $page
     */
    private ?int $page;

    /**
     * @var int|null $perPage
     */
    private ?int $perPage;

    /**
     * @var string|null $search
     */
    private ?string $search;

    /**
     * @var string|null $sortBy
     */
    private ?string $sortBy;

    /**
     * @var string|null $sortDirection
     */
    private ?string $sortDirection;

    /**
    * @return \Hostinger\Model\ReachV1ContactsSegmentsProfileFilterContactsRequestConditionsInner[]
    */
    public function getConditions(): array
    {
        return $this->conditions;
    }

    /**
     * @param \Hostinger\Model\ReachV1ContactsSegmentsProfileFilterContactsRequestConditionsInner[] $conditions Conditions a contact must satisfy to appear in the preview
     */
    public function setConditions(array $conditions): self
    {
        $this->conditions = $conditions;

        return $this;
    }
    /**
    * @return string
    */
    public function getLogic(): string
    {
        return $this->logic;
    }

    /**
     * @param string $logic How to combine multiple conditions
     */
    public function setLogic(string $logic): self
    {
        $this->logic = $logic;

        return $this;
    }
    /**
    * @return int|null
    */
    public function getPage(): ?int
    {
        return $this->page;
    }

    /**
     * @param int|null $page Page number
     */
    public function setPage(?int $page): self
    {
        $this->page = $page;

        return $this;
    }
    /**
    * @return int|null
    */
    public function getPerPage(): ?int
    {
        return $this->perPage;
    }

    /**
     * @param int|null $perPage Number of items per page
     */
    public function setPerPage(?int $perPage): self
    {
        $this->perPage = $perPage;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getSearch(): ?string
    {
        return $this->search;
    }

    /**
     * @param string|null $search Narrow the preview to contacts whose email matches
     */
    public function setSearch(?string $search): self
    {
        $this->search = $search;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getSortBy(): ?string
    {
        return $this->sortBy;
    }

    /**
     * @param string|null $sortBy sortBy
     */
    public function setSortBy(?string $sortBy): self
    {
        $this->sortBy = $sortBy;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getSortDirection(): ?string
    {
        return $this->sortDirection;
    }

    /**
     * @param string|null $sortDirection sortDirection
     */
    public function setSortDirection(?string $sortDirection): self
    {
        $this->sortDirection = $sortDirection;

        return $this;
    }
}

