<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.46.3
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class ReachV1CampaignsStoreRequestMetadata 
{

    /**
     * @var string|null $preheader
     */
    private ?string $preheader;

    /**
     * @var string|null $source
     */
    private ?string $source;

    /**
    * @return string|null
    */
    public function getPreheader(): ?string
    {
        return $this->preheader;
    }

    /**
     * @param string|null $preheader Preview text shown after the subject line in the inbox.
     */
    public function setPreheader(?string $preheader): self
    {
        $this->preheader = $preheader;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getSource(): ?string
    {
        return $this->source;
    }

    /**
     * @param string|null $source Where the campaign was created from.
     */
    public function setSource(?string $source): self
    {
        $this->source = $source;

        return $this;
    }
}

