<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.36.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class ReachV1FormsFormTemplateDetailsResource 
{

    /**
     * @var string|null $uuid
     */
    private ?string $uuid = null;

    /**
     * @var string|null $path
     */
    private ?string $path = null;

    /**
     * @var string|null $url
     */
    private ?string $url = null;

    /**
    * @return string|null
    */
    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    /**
     * @param string|null $uuid uuid
     */
    public function setUuid(?string $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getPath(): ?string
    {
        return $this->path;
    }

    /**
     * @param string|null $path Storage path of the template HTML, relative to the storage directory of this profile. `url` already includes that prefix, so prefer it unless you resolve storage paths yourself.
     */
    public function setPath(?string $path): self
    {
        $this->path = $path;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * @param string|null $url Publicly reachable URL of the template HTML.
     */
    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }
}

