<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 0.0.97
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Hostinger\ObjectSerializer;

class VPSV1VirtualMachineRecreateRequest 
{
    /**
     * @var int $templateId
     */
    private $templateId;

    /**
     * @var string $password
     */
    private $password;

    /**
     * @var string $panelPassword
     */
    private $panelPassword;

    /**
     * @var int $postInstallScriptId
     */
    private $postInstallScriptId;

    /**
     * @return int
     */
    public function getTemplateId()
    {
        return $this->templateId;
    }

    /**
     * @param int $templateId
     */
    public function setTemplateId($templateId): self
    {
        $this->templateId = $templateId;

        return $this;
    }
    /**
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param string $password
     */
    public function setPassword($password): self
    {
        $this->password = $password;

        return $this;
    }
    /**
     * @return string
     */
    public function getPanelPassword()
    {
        return $this->panelPassword;
    }

    /**
     * @param string $panelPassword
     */
    public function setPanelPassword($panelPassword): self
    {
        $this->panelPassword = $panelPassword;

        return $this;
    }
    /**
     * @return int
     */
    public function getPostInstallScriptId()
    {
        return $this->postInstallScriptId;
    }

    /**
     * @param int $postInstallScriptId
     */
    public function setPostInstallScriptId($postInstallScriptId): self
    {
        $this->postInstallScriptId = $postInstallScriptId;

        return $this;
    }
}

