<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 0.1.16
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class VPSV1BackupBackupResource 
{

    /**
     * @var int|null $id
     */
    private ?int $id;

    /**
     * @var int|null $size
     */
    private ?int $size;

    /**
     * @var int|null $restoreTime
     */
    private ?int $restoreTime;

    /**
     * @var string|null $location
     */
    private ?string $location;

    /**
     * @var \DateTime|null $createdAt
     */
    private ?\DateTime $createdAt;

    /**
    * @return int|null
    */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @param int|null $id Backup ID
     */
    public function setId(?int $id): self
    {
        $this->id = $id;

        return $this;
    }
    /**
    * @return int|null
    */
    public function getSize(): ?int
    {
        return $this->size;
    }

    /**
     * @param int|null $size Backup size in kilobytes
     */
    public function setSize(?int $size): self
    {
        $this->size = $size;

        return $this;
    }
    /**
    * @return int|null
    */
    public function getRestoreTime(): ?int
    {
        return $this->restoreTime;
    }

    /**
     * @param int|null $restoreTime Estimated backup restore time in seconds
     */
    public function setRestoreTime(?int $restoreTime): self
    {
        $this->restoreTime = $restoreTime;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getLocation(): ?string
    {
        return $this->location;
    }

    /**
     * @param string|null $location Location of the backup
     */
    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }
    /**
    * @return \DateTime|null
    */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime|null $createdAt createdAt
     */
    public function setCreatedAt(?\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

