<?php
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 0.0.96
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Hostinger\ObjectSerializer;

/**
 * @implements ArrayAccess<string, mixed>
 */
class VPSV1VirtualMachineVirtualMachineResource 
{
    /**
     * @param int $id
     * @param int|null $firewallGroupId
     * @param string|null $subscriptionId
     * @param string|null $plan
     * @param string $hostname
     * @param string $state
     * @param string $actionsLock
     * @param int $cpus
     * @param int $memory
     * @param int $disk
     * @param int $bandwidth
     * @param string|null $ns1
     * @param string|null $ns2
     * @param \Hostinger\Model\VPSV1IPAddressIPAddressCollection|null $ipv4
     * @param \Hostinger\Model\VPSV1IPAddressIPAddressCollection|null $ipv6
     * @param \Hostinger\Model\VPSV1TemplateTemplateResource|null $template
     * @param \DateTime $createdAt
     */
    protected static $openAPIModelName = 'VPSV1VirtualMachineVirtualMachineResource';
    public function __construct(
        private $id,
        private $firewallGroupId = null,
        private $subscriptionId = null,
        private $plan = null,
        private $hostname,
        private $state,
        private $actionsLock,
        private $cpus,
        private $memory,
        private $disk,
        private $bandwidth,
        private $ns1 = null,
        private $ns2 = null,
        private $ipv4 = null,
        private $ipv6 = null,
        private $template = null,
        private $createdAt,
    ) {
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     *
     * @return self
     */
    public function setId($id): self
    {
        $this->id = $id;

        return $this;
    }
    /**
     * @return int|null
     */
    public function getFirewallGroupId()
    {
        return $this->firewallGroupId;
    }

    /**
     * @param int|null $firewallGroupId
     *
     * @return self
     */
    public function setFirewallGroupId($firewallGroupId): self
    {
        $this->firewallGroupId = $firewallGroupId;

        return $this;
    }
    /**
     * @return string|null
     */
    public function getSubscriptionId()
    {
        return $this->subscriptionId;
    }

    /**
     * @param string|null $subscriptionId
     *
     * @return self
     */
    public function setSubscriptionId($subscriptionId): self
    {
        $this->subscriptionId = $subscriptionId;

        return $this;
    }
    /**
     * @return string|null
     */
    public function getPlan()
    {
        return $this->plan;
    }

    /**
     * @param string|null $plan
     *
     * @return self
     */
    public function setPlan($plan): self
    {
        $this->plan = $plan;

        return $this;
    }
    /**
     * @return string
     */
    public function getHostname()
    {
        return $this->hostname;
    }

    /**
     * @param string $hostname
     *
     * @return self
     */
    public function setHostname($hostname): self
    {
        $this->hostname = $hostname;

        return $this;
    }
    /**
     * @return string
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * @param string $state
     *
     * @return self
     */
    public function setState($state): self
    {
        $this->state = $state;

        return $this;
    }
    /**
     * @return string
     */
    public function getActionsLock()
    {
        return $this->actionsLock;
    }

    /**
     * @param string $actionsLock
     *
     * @return self
     */
    public function setActionsLock($actionsLock): self
    {
        $this->actionsLock = $actionsLock;

        return $this;
    }
    /**
     * @return int
     */
    public function getCpus()
    {
        return $this->cpus;
    }

    /**
     * @param int $cpus
     *
     * @return self
     */
    public function setCpus($cpus): self
    {
        $this->cpus = $cpus;

        return $this;
    }
    /**
     * @return int
     */
    public function getMemory()
    {
        return $this->memory;
    }

    /**
     * @param int $memory
     *
     * @return self
     */
    public function setMemory($memory): self
    {
        $this->memory = $memory;

        return $this;
    }
    /**
     * @return int
     */
    public function getDisk()
    {
        return $this->disk;
    }

    /**
     * @param int $disk
     *
     * @return self
     */
    public function setDisk($disk): self
    {
        $this->disk = $disk;

        return $this;
    }
    /**
     * @return int
     */
    public function getBandwidth()
    {
        return $this->bandwidth;
    }

    /**
     * @param int $bandwidth
     *
     * @return self
     */
    public function setBandwidth($bandwidth): self
    {
        $this->bandwidth = $bandwidth;

        return $this;
    }
    /**
     * @return string|null
     */
    public function getNs1()
    {
        return $this->ns1;
    }

    /**
     * @param string|null $ns1
     *
     * @return self
     */
    public function setNs1($ns1): self
    {
        $this->ns1 = $ns1;

        return $this;
    }
    /**
     * @return string|null
     */
    public function getNs2()
    {
        return $this->ns2;
    }

    /**
     * @param string|null $ns2
     *
     * @return self
     */
    public function setNs2($ns2): self
    {
        $this->ns2 = $ns2;

        return $this;
    }
    /**
     * @return \Hostinger\Model\VPSV1IPAddressIPAddressCollection|null
     */
    public function getIpv4()
    {
        return $this->ipv4;
    }

    /**
     * @param \Hostinger\Model\VPSV1IPAddressIPAddressCollection|null $ipv4
     *
     * @return self
     */
    public function setIpv4($ipv4): self
    {
        $this->ipv4 = $ipv4;

        return $this;
    }
    /**
     * @return \Hostinger\Model\VPSV1IPAddressIPAddressCollection|null
     */
    public function getIpv6()
    {
        return $this->ipv6;
    }

    /**
     * @param \Hostinger\Model\VPSV1IPAddressIPAddressCollection|null $ipv6
     *
     * @return self
     */
    public function setIpv6($ipv6): self
    {
        $this->ipv6 = $ipv6;

        return $this;
    }
    /**
     * @return \Hostinger\Model\VPSV1TemplateTemplateResource|null
     */
    public function getTemplate()
    {
        return $this->template;
    }

    /**
     * @param \Hostinger\Model\VPSV1TemplateTemplateResource|null $template
     *
     * @return self
     */
    public function setTemplate($template): self
    {
        $this->template = $template;

        return $this;
    }
    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     *
     * @return self
     */
    public function setCreatedAt($createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

