<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 0.0.96
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Hostinger\ObjectSerializer;

class VPSV1DataCenterDataCenterResource 
{
    /**
     * @var int $id
     */
    private $id;

    /**
     * @var string|null $name
     */
    private $name = null;

    /**
     * @var string|null $location
     */
    private $location = null;

    /**
     * @var string|null $city
     */
    private $city = null;

    /**
     * @var string|null $continent
     */
    private $continent = null;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id): self
    {
        $this->id = $id;

        return $this;
    }
    /**
     * @return string|null
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string|null $name
     */
    public function setName($name): self
    {
        $this->name = $name;

        return $this;
    }
    /**
     * @return string|null
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * @param string|null $location
     */
    public function setLocation($location): self
    {
        $this->location = $location;

        return $this;
    }
    /**
     * @return string|null
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param string|null $city
     */
    public function setCity($city): self
    {
        $this->city = $city;

        return $this;
    }
    /**
     * @return string|null
     */
    public function getContinent()
    {
        return $this->continent;
    }

    /**
     * @param string|null $continent
     */
    public function setContinent($continent): self
    {
        $this->continent = $continent;

        return $this;
    }
}

