<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.46.2
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class VPSV1FirewallRulesReplaceRequest 
{

    /**
     * @var \Hostinger\Model\VPSV1FirewallRulesStoreRequest[] $rules
     */
    private array $rules;

    /**
     * @var bool|null $sync
     */
    private ?bool $sync;

    /**
    * @return \Hostinger\Model\VPSV1FirewallRulesStoreRequest[]
    */
    public function getRules(): array
    {
        return $this->rules;
    }

    /**
     * @param \Hostinger\Model\VPSV1FirewallRulesStoreRequest[] $rules The complete set of firewall rules that atomically replaces all existing rules in the group
     */
    public function setRules(array $rules): self
    {
        $this->rules = $rules;

        return $this;
    }
    /**
    * @return bool|null
    */
    public function getSync(): ?bool
    {
        return $this->sync;
    }

    /**
     * @param bool|null $sync Synchronize the firewall group to all its virtual machines after replacing the rules
     */
    public function setSync(?bool $sync): self
    {
        $this->sync = $sync;

        return $this;
    }
}

