<?php
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 0.0.96
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Hostinger\ObjectSerializer;

/**
 * @implements ArrayAccess<string, mixed>
 */
class VPSV1VirtualMachineSetupRequest 
{
    /**
     * @param int $templateId
     * @param int $dataCenterId
     * @param int $postInstallScriptId
     * @param string $password
     * @param string $hostname
     * @param bool $installMonarx
     * @param bool $enableBackups
     * @param string $ns1
     * @param string $ns2
     * @param \Hostinger\Model\VPSV1VirtualMachineSetupRequestPublicKey $publicKey
     */
    protected static $openAPIModelName = 'VPSV1VirtualMachineSetupRequest';
    public function __construct(
        private $templateId,
        private $dataCenterId,
        private $postInstallScriptId,
        private $password,
        private $hostname,
        private $installMonarx,
        private $enableBackups,
        private $ns1,
        private $ns2,
        private $publicKey,
    ) {
    }

    /**
     * @return int
     */
    public function getTemplateId()
    {
        return $this->templateId;
    }

    /**
     * @param int $templateId
     *
     * @return self
     */
    public function setTemplateId($templateId): self
    {
        $this->templateId = $templateId;

        return $this;
    }
    /**
     * @return int
     */
    public function getDataCenterId()
    {
        return $this->dataCenterId;
    }

    /**
     * @param int $dataCenterId
     *
     * @return self
     */
    public function setDataCenterId($dataCenterId): self
    {
        $this->dataCenterId = $dataCenterId;

        return $this;
    }
    /**
     * @return int
     */
    public function getPostInstallScriptId()
    {
        return $this->postInstallScriptId;
    }

    /**
     * @param int $postInstallScriptId
     *
     * @return self
     */
    public function setPostInstallScriptId($postInstallScriptId): self
    {
        $this->postInstallScriptId = $postInstallScriptId;

        return $this;
    }
    /**
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param string $password
     *
     * @return self
     */
    public function setPassword($password): self
    {
        $this->password = $password;

        return $this;
    }
    /**
     * @return string
     */
    public function getHostname()
    {
        return $this->hostname;
    }

    /**
     * @param string $hostname
     *
     * @return self
     */
    public function setHostname($hostname): self
    {
        $this->hostname = $hostname;

        return $this;
    }
    /**
     * @return bool
     */
    public function getInstallMonarx()
    {
        return $this->installMonarx;
    }

    /**
     * @param bool $installMonarx
     *
     * @return self
     */
    public function setInstallMonarx($installMonarx): self
    {
        $this->installMonarx = $installMonarx;

        return $this;
    }
    /**
     * @return bool
     */
    public function getEnableBackups()
    {
        return $this->enableBackups;
    }

    /**
     * @param bool $enableBackups
     *
     * @return self
     */
    public function setEnableBackups($enableBackups): self
    {
        $this->enableBackups = $enableBackups;

        return $this;
    }
    /**
     * @return string
     */
    public function getNs1()
    {
        return $this->ns1;
    }

    /**
     * @param string $ns1
     *
     * @return self
     */
    public function setNs1($ns1): self
    {
        $this->ns1 = $ns1;

        return $this;
    }
    /**
     * @return string
     */
    public function getNs2()
    {
        return $this->ns2;
    }

    /**
     * @param string $ns2
     *
     * @return self
     */
    public function setNs2($ns2): self
    {
        $this->ns2 = $ns2;

        return $this;
    }
    /**
     * @return \Hostinger\Model\VPSV1VirtualMachineSetupRequestPublicKey
     */
    public function getPublicKey()
    {
        return $this->publicKey;
    }

    /**
     * @param \Hostinger\Model\VPSV1VirtualMachineSetupRequestPublicKey $publicKey
     *
     * @return self
     */
    public function setPublicKey($publicKey): self
    {
        $this->publicKey = $publicKey;

        return $this;
    }
}

