<?php

/**
 * Hostinger API PHP SDK
 *
 * API Version: 0.0.1-beta
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Hostinger\ObjectSerializer;

/**
 * @implements ArrayAccess<string, mixed>
 */
class VPSV1VirtualMachineVirtualMachineResource implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      */
    protected static string $openAPIModelName = 'VPS.V1.VirtualMachine.VirtualMachineResource';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'id' => 'int',
        'firewall_group_id' => 'int',
        'subscription_id' => 'string',
        'plan' => 'string',
        'hostname' => 'string',
        'state' => 'string',
        'actions_lock' => 'string',
        'cpus' => 'int',
        'memory' => 'int',
        'disk' => 'int',
        'bandwidth' => 'int',
        'ns1' => 'string',
        'ns2' => 'string',
        'ipv4' => '\Hostinger\Model\VPSV1VirtualMachineVirtualMachineResourceIpv4',
        'ipv6' => '\Hostinger\Model\VPSV1VirtualMachineVirtualMachineResourceIpv6',
        'template' => '\Hostinger\Model\VPSV1VirtualMachineVirtualMachineResourceTemplate',
        'created_at' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'id' => null,
        'firewall_group_id' => null,
        'subscription_id' => null,
        'plan' => null,
        'hostname' => null,
        'state' => null,
        'actions_lock' => null,
        'cpus' => null,
        'memory' => null,
        'disk' => null,
        'bandwidth' => null,
        'ns1' => null,
        'ns2' => null,
        'ipv4' => null,
        'ipv6' => null,
        'template' => null,
        'created_at' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'id' => false,
        'firewall_group_id' => true,
        'subscription_id' => true,
        'plan' => true,
        'hostname' => false,
        'state' => false,
        'actions_lock' => false,
        'cpus' => false,
        'memory' => false,
        'disk' => false,
        'bandwidth' => false,
        'ns1' => true,
        'ns2' => true,
        'ipv4' => true,
        'ipv6' => true,
        'template' => true,
        'created_at' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'id' => 'id',
        'firewall_group_id' => 'firewall_group_id',
        'subscription_id' => 'subscription_id',
        'plan' => 'plan',
        'hostname' => 'hostname',
        'state' => 'state',
        'actions_lock' => 'actions_lock',
        'cpus' => 'cpus',
        'memory' => 'memory',
        'disk' => 'disk',
        'bandwidth' => 'bandwidth',
        'ns1' => 'ns1',
        'ns2' => 'ns2',
        'ipv4' => 'ipv4',
        'ipv6' => 'ipv6',
        'template' => 'template',
        'created_at' => 'created_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'id' => 'setId',
        'firewall_group_id' => 'setFirewallGroupId',
        'subscription_id' => 'setSubscriptionId',
        'plan' => 'setPlan',
        'hostname' => 'setHostname',
        'state' => 'setState',
        'actions_lock' => 'setActionsLock',
        'cpus' => 'setCpus',
        'memory' => 'setMemory',
        'disk' => 'setDisk',
        'bandwidth' => 'setBandwidth',
        'ns1' => 'setNs1',
        'ns2' => 'setNs2',
        'ipv4' => 'setIpv4',
        'ipv6' => 'setIpv6',
        'template' => 'setTemplate',
        'created_at' => 'setCreatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'id' => 'getId',
        'firewall_group_id' => 'getFirewallGroupId',
        'subscription_id' => 'getSubscriptionId',
        'plan' => 'getPlan',
        'hostname' => 'getHostname',
        'state' => 'getState',
        'actions_lock' => 'getActionsLock',
        'cpus' => 'getCpus',
        'memory' => 'getMemory',
        'disk' => 'getDisk',
        'bandwidth' => 'getBandwidth',
        'ns1' => 'getNs1',
        'ns2' => 'getNs2',
        'ipv4' => 'getIpv4',
        'ipv6' => 'getIpv6',
        'template' => 'getTemplate',
        'created_at' => 'getCreatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const STATE_RUNNING = 'running';
    public const STATE_STOPPED = 'stopped';
    public const STATE_CREATING = 'creating';
    public const STATE_INITIAL = 'initial';
    public const ACTIONS_LOCK_UNLOCKED = 'unlocked';
    public const ACTIONS_LOCK_LOCKED = 'locked';

    /**
     * @return array<string>
     */
    public function getStateAllowableValues()
    {
        return [
            self::STATE_RUNNING,
            self::STATE_STOPPED,
            self::STATE_CREATING,
            self::STATE_INITIAL,
        ];
    }

    /**
     * @return array<string>
     */
    public function getActionsLockAllowableValues()
    {
        return [
            self::ACTIONS_LOCK_UNLOCKED,
            self::ACTIONS_LOCK_LOCKED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array<string, mixed>
     */
    protected array $container = [];

    /**
     * @param array<string, mixed> $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = [])
    {
        $this->setIfExists('id', $data, null);
        $this->setIfExists('firewall_group_id', $data, null);
        $this->setIfExists('subscription_id', $data, null);
        $this->setIfExists('plan', $data, null);
        $this->setIfExists('hostname', $data, null);
        $this->setIfExists('state', $data, null);
        $this->setIfExists('actions_lock', $data, null);
        $this->setIfExists('cpus', $data, null);
        $this->setIfExists('memory', $data, null);
        $this->setIfExists('disk', $data, null);
        $this->setIfExists('bandwidth', $data, null);
        $this->setIfExists('ns1', $data, null);
        $this->setIfExists('ns2', $data, null);
        $this->setIfExists('ipv4', $data, null);
        $this->setIfExists('ipv6', $data, null);
        $this->setIfExists('template', $data, null);
        $this->setIfExists('created_at', $data, null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * @return array<string> invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        $allowedValues = $this->getStateAllowableValues();
        if (!is_null($this->container['state']) && !in_array($this->container['state'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'state', must be one of '%s'",
                $this->container['state'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getActionsLockAllowableValues();
        if (!is_null($this->container['actions_lock']) && !in_array($this->container['actions_lock'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'actions_lock', must be one of '%s'",
                $this->container['actions_lock'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model return true if all passed
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->container['id'];
    }

    /**
     * @param int|null $id Virtual machine ID
     */
    public function setId(?int $id): static
    {
        if (is_null($id)) {
            throw new InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getFirewallGroupId(): ?int
    {
        return $this->container['firewall_group_id'];
    }

    /**
     * @param int|null $firewall_group_id Active firewall ID, `null` if disabled
     */
    public function setFirewallGroupId(?int $firewall_group_id): static
    {
        if (is_null($firewall_group_id)) {
            array_push($this->openAPINullablesSetToNull, 'firewall_group_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('firewall_group_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['firewall_group_id'] = $firewall_group_id;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getSubscriptionId(): ?string
    {
        return $this->container['subscription_id'];
    }

    /**
     * @param string|null $subscription_id Subscription ID
     */
    public function setSubscriptionId(?string $subscription_id): static
    {
        if (is_null($subscription_id)) {
            array_push($this->openAPINullablesSetToNull, 'subscription_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('subscription_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['subscription_id'] = $subscription_id;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getPlan(): ?string
    {
        return $this->container['plan'];
    }

    /**
     * @param string|null $plan VPS plan name
     */
    public function setPlan(?string $plan): static
    {
        if (is_null($plan)) {
            array_push($this->openAPINullablesSetToNull, 'plan');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('plan', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['plan'] = $plan;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getHostname(): ?string
    {
        return $this->container['hostname'];
    }

    /**
     * @param string|null $hostname hostname
     */
    public function setHostname(?string $hostname): static
    {
        if (is_null($hostname)) {
            throw new InvalidArgumentException('non-nullable hostname cannot be null');
        }
        $this->container['hostname'] = $hostname;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getState(): ?string
    {
        return $this->container['state'];
    }

    /**
     * @param string|null $state state
     */
    public function setState(?string $state): static
    {
        if (is_null($state)) {
            throw new InvalidArgumentException('non-nullable state cannot be null');
        }
        $allowedValues = $this->getStateAllowableValues();
        if (!in_array($state, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'state', must be one of '%s'",
                    $state,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getActionsLock(): ?string
    {
        return $this->container['actions_lock'];
    }

    /**
     * @param string|null $actions_lock actions_lock
     */
    public function setActionsLock(?string $actions_lock): static
    {
        if (is_null($actions_lock)) {
            throw new InvalidArgumentException('non-nullable actions_lock cannot be null');
        }
        $allowedValues = $this->getActionsLockAllowableValues();
        if (!in_array($actions_lock, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'actions_lock', must be one of '%s'",
                    $actions_lock,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['actions_lock'] = $actions_lock;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getCpus(): ?int
    {
        return $this->container['cpus'];
    }

    /**
     * @param int|null $cpus CPUs count assigned to virtual machine
     */
    public function setCpus(?int $cpus): static
    {
        if (is_null($cpus)) {
            throw new InvalidArgumentException('non-nullable cpus cannot be null');
        }
        $this->container['cpus'] = $cpus;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getMemory(): ?int
    {
        return $this->container['memory'];
    }

    /**
     * @param int|null $memory Memory available to virtual machine (in megabytes)
     */
    public function setMemory(?int $memory): static
    {
        if (is_null($memory)) {
            throw new InvalidArgumentException('non-nullable memory cannot be null');
        }
        $this->container['memory'] = $memory;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getDisk(): ?int
    {
        return $this->container['disk'];
    }

    /**
     * @param int|null $disk Virtual machine disk size (in megabytes)
     */
    public function setDisk(?int $disk): static
    {
        if (is_null($disk)) {
            throw new InvalidArgumentException('non-nullable disk cannot be null');
        }
        $this->container['disk'] = $disk;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getBandwidth(): ?int
    {
        return $this->container['bandwidth'];
    }

    /**
     * @param int|null $bandwidth Monthly internet traffic available to virtual machine (in megabytes)
     */
    public function setBandwidth(?int $bandwidth): static
    {
        if (is_null($bandwidth)) {
            throw new InvalidArgumentException('non-nullable bandwidth cannot be null');
        }
        $this->container['bandwidth'] = $bandwidth;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getNs1(): ?string
    {
        return $this->container['ns1'];
    }

    /**
     * @param string|null $ns1 Primary DNS resolver
     */
    public function setNs1(?string $ns1): static
    {
        if (is_null($ns1)) {
            array_push($this->openAPINullablesSetToNull, 'ns1');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ns1', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ns1'] = $ns1;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getNs2(): ?string
    {
        return $this->container['ns2'];
    }

    /**
     * @param string|null $ns2 Secondary DNS resolver
     */
    public function setNs2(?string $ns2): static
    {
        if (is_null($ns2)) {
            array_push($this->openAPINullablesSetToNull, 'ns2');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ns2', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ns2'] = $ns2;

        return $this;
    }

    /**
     * @return \Hostinger\Model\VPSV1VirtualMachineVirtualMachineResourceIpv4|null
     */
    public function getIpv4(): ?\Hostinger\Model\VPSV1VirtualMachineVirtualMachineResourceIpv4
    {
        return $this->container['ipv4'];
    }

    /**
     * @param \Hostinger\Model\VPSV1VirtualMachineVirtualMachineResourceIpv4|null $ipv4 ipv4
     */
    public function setIpv4(?\Hostinger\Model\VPSV1VirtualMachineVirtualMachineResourceIpv4 $ipv4): static
    {
        if (is_null($ipv4)) {
            array_push($this->openAPINullablesSetToNull, 'ipv4');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ipv4', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ipv4'] = $ipv4;

        return $this;
    }

    /**
     * @return \Hostinger\Model\VPSV1VirtualMachineVirtualMachineResourceIpv6|null
     */
    public function getIpv6(): ?\Hostinger\Model\VPSV1VirtualMachineVirtualMachineResourceIpv6
    {
        return $this->container['ipv6'];
    }

    /**
     * @param \Hostinger\Model\VPSV1VirtualMachineVirtualMachineResourceIpv6|null $ipv6 ipv6
     */
    public function setIpv6(?\Hostinger\Model\VPSV1VirtualMachineVirtualMachineResourceIpv6 $ipv6): static
    {
        if (is_null($ipv6)) {
            array_push($this->openAPINullablesSetToNull, 'ipv6');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ipv6', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ipv6'] = $ipv6;

        return $this;
    }

    /**
     * @return \Hostinger\Model\VPSV1VirtualMachineVirtualMachineResourceTemplate|null
     */
    public function getTemplate(): ?\Hostinger\Model\VPSV1VirtualMachineVirtualMachineResourceTemplate
    {
        return $this->container['template'];
    }

    /**
     * @param \Hostinger\Model\VPSV1VirtualMachineVirtualMachineResourceTemplate|null $template template
     */
    public function setTemplate(?\Hostinger\Model\VPSV1VirtualMachineVirtualMachineResourceTemplate $template): static
    {
        if (is_null($template)) {
            array_push($this->openAPINullablesSetToNull, 'template');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('template', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['template'] = $template;

        return $this;
    }

    /**
     * @return \DateTime|null
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->container['created_at'];
    }

    /**
     * @param \DateTime|null $created_at created_at
     */
    public function setCreatedAt(?\DateTime $created_at): static
    {
        if (is_null($created_at)) {
            throw new InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


