<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.15.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class WordPressV1InstallationsCheckIsValidRequest 
{

    /**
     * @var string[] $softwareIds
     */
    private array $softwareIds;

    /**
     * @var bool|null $force
     */
    private ?bool $force;

    /**
    * @return string[]
    */
    public function getSoftwareIds(): array
    {
        return $this->softwareIds;
    }

    /**
     * @param string[] $softwareIds WordPress installation (software) identifiers to validate.
     */
    public function setSoftwareIds(array $softwareIds): self
    {
        $this->softwareIds = $softwareIds;

        return $this;
    }
    /**
    * @return bool|null
    */
    public function getForce(): ?bool
    {
        return $this->force;
    }

    /**
     * @param bool|null $force Force fresh validation without cache. Preferable for troubleshooting purposes.
     */
    public function setForce(?bool $force): self
    {
        $this->force = $force;

        return $this;
    }
}

