<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.7.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class WordPressV1PluginsUpdateHostingerPluginRequest 
{
    /**
     * @var string
     */
    public const SLUG_HOSTINGER = 'hostinger';
    /**
     * @var string
     */
    public const SLUG_HOSTINGER_AI_ASSISTANT = 'hostinger-ai-assistant';
    /**
     * @var string
     */
    public const SLUG_HOSTINGER_AFFILIATE_PLUGIN = 'hostinger-affiliate-plugin';
    /**
     * @var string
     */
    public const SLUG_HOSTINGER_EASY_ONBOARDING = 'hostinger-easy-onboarding';
    /**
     * @var string
     */
    public const SLUG_HOSTINGER_REACH = 'hostinger-reach';

    /**
     * @var string $slug
     */
    private string $slug;

    /**
    * @return string
    */
    public function getSlug(): string
    {
        return $this->slug;
    }

    /**
     * @param string $slug Slug of the Hostinger plugin to update to its latest version.
     */
    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

