<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.13.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class WordPressV1InstallationsUpdateResource 
{
    /**
     * @var string
     */
    public const TYPE_MAJOR = 'major';
    /**
     * @var string
     */
    public const TYPE_MINOR = 'minor';

    /**
     * @var string|null $version
     */
    private ?string $version;

    /**
     * @var string|null $type
     */
    private ?string $type;

    /**
     * @var string|null $url
     */
    private ?string $url;

    /**
    * @return string|null
    */
    public function getVersion(): ?string
    {
        return $this->version;
    }

    /**
     * @param string|null $version Available WordPress core version
     */
    public function setVersion(?string $version): self
    {
        $this->version = $version;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * @param string|null $type Update type
     */
    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * @param string|null $url Download URL for the update package
     */
    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }
}

