<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.59.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class WordPressV1McpExecuteMcpToolRequest 
{
    /**
     * @var string
     */
    public const SERVER_MCP_ADAPTER_DEFAULT_SERVER = 'mcp-adapter-default-server';
    /**
     * @var string
     */
    public const SERVER_HOSTINGER_AI_ASSISTANT_MCP_SERVER = 'hostinger-ai-assistant-mcp-server';

    /**
     * @var string $toolName
     */
    private string $toolName;

    /**
     * @var array<string,mixed>|null $parameters
     */
    private ?array $parameters;

    /**
     * @var string|null $server
     */
    private ?string $server = null;

    /**
    * @return string
    */
    public function getToolName(): string
    {
        return $this->toolName;
    }

    /**
     * @param string $toolName Tool name as returned by the List MCP tools endpoint.
     */
    public function setToolName(string $toolName): self
    {
        $this->toolName = $toolName;

        return $this;
    }
    /**
    * @return array<string,mixed>|null
    */
    public function getParameters(): ?array
    {
        return $this->parameters;
    }

    /**
     * @param array<string,mixed>|null $parameters Tool input matching the input schema returned by the Show MCP tool info endpoint.
     */
    public function setParameters(?array $parameters): self
    {
        $this->parameters = $parameters;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getServer(): ?string
    {
        return $this->server;
    }

    /**
     * @param string|null $server MCP server exposing the tool. Defaults to the mcp-adapter default server.
     */
    public function setServer(?string $server): self
    {
        $this->server = $server;

        return $this;
    }
}

