<?php
/** @noinspection PhpMissingFieldTypeInspection */
/** @noinspection PhpPluralMixedCanBeReplacedWithArrayInspection */
/** @noinspection PhpMissingParamTypeInspection */
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.7.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Model;

class WordPressV1PluginsPluginResource 
{

    /**
     * @var string|null $slug
     */
    private ?string $slug;

    /**
     * @var string|null $title
     */
    private ?string $title;

    /**
     * @var \Hostinger\Model\WordPressV1PluginsPluginResourceIcons|null $icons
     */
    private ?\Hostinger\Model\WordPressV1PluginsPluginResourceIcons $icons = null;

    /**
     * @var string|null $description
     */
    private ?string $description;

    /**
    * @return string|null
    */
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /**
     * @param string|null $slug Plugin slug used when installing the plugin
     */
    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string|null $title Human readable plugin name
     */
    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }
    /**
    * @return \Hostinger\Model\WordPressV1PluginsPluginResourceIcons|null
    */
    public function getIcons(): ?\Hostinger\Model\WordPressV1PluginsPluginResourceIcons
    {
        return $this->icons;
    }

    /**
     * @param \Hostinger\Model\WordPressV1PluginsPluginResourceIcons|null $icons icons
     */
    public function setIcons(?\Hostinger\Model\WordPressV1PluginsPluginResourceIcons $icons): self
    {
        $this->icons = $icons;

        return $this;
    }
    /**
    * @return string|null
    */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string|null $description Short plugin description
     */
    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

