<?php
/** @noinspection PhpMissingReturnTypeInspection */
/** @noinspection PhpFullyQualifiedNameUsageInspection */

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.18.2
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\GuzzleException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Exception\ExceptionInterface;
use Symfony\Component\Serializer\Serializer;
use Hostinger\ApiException;
use Hostinger\Configuration;
use Hostinger\ObjectSerializer;

class MailOrdersApi
{
    protected ClientInterface $client;

    protected Configuration $config;

    protected Serializer $serializer;

    public function __construct(
        ?Configuration $config = null,
        ?ClientInterface $client = null,
    ) {
        $this->serializer = ObjectSerializer::getSerializer();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->client = $client ?: new Client([
            'base_uri' => $this->config->getHost(),
        ]);
    }

    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * @return \Hostinger\Model\MailV1OrdersPlanResource
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function getOrderPlanV1(string $orderId)
    {
        $request = new Request(
            method: 'GET',
            uri: $this->buildResourcePath('/api/mail/v1/orders/{orderId}/plan', [
                'orderId' => $orderId
            ]),
            headers: $this->getHeaders(),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }

        return $this->serializer->deserialize($response->getBody()->getContents(), '\Hostinger\Model\MailV1OrdersPlanResource', JsonEncoder::FORMAT);
    }

    /**
     * @return \Hostinger\Model\MailListOrdersV1200Response
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws ExceptionInterface
     */
    public function listOrdersV1(?string $domain = null, ?string $status = null, ?bool $isTrial = null, ?string $sort = '-created_at', ?int $page = null, ?int $perPage = 25)
    {
        $query = http_build_query(
            array_filter(
                $this->serializer->normalize([
                        'domain' => $domain,
                        'status' => $status,
                        'is_trial' => $isTrial,
                        'sort' => $sort,
                        'page' => $page,
                        'per_page' => $perPage,
                ])
            )
        );

        $request = new Request(
            method: 'GET',
            uri: '/api/mail/v1/orders' . '?' . $query,
            headers: $this->getHeaders(),
        );

        try {
            $response = $this->client->send($request, $this->createHttpClientOption());
        } catch (RequestException $e) {
            throw ApiException::fromRequestException($e);
        } catch (ConnectException $e) {
            throw ApiException::fromConnectException($e);
        }

        return $this->serializer->deserialize($response->getBody()->getContents(), '\Hostinger\Model\MailListOrdersV1200Response', JsonEncoder::FORMAT);
    }

    /**
     * @param array<string, mixed> $values
     */
    private function buildResourcePath(string $path, array $values): string
    {
        foreach ($values as $key => $value) {
            if (is_array($value)) {
                $value = implode(',', $value);
            }

            $path = str_replace('{' . $key . '}', $value, $path);
        }

        return $path;
    }

    /**
     * @return array<string, string>
     */
    private function getHeaders(): array
    {
        return [
            'Authorization' => 'Bearer ' . $this->config->getAccessToken(),
            'Content-Type' => 'application/json',
            'User-Agent' => $this->config->getUserAgent(),
        ];
    }

    /**
     * @return array<string, string>
     */
    private function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
