<?php

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.42.3
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Test\Model;

use PHPUnit\Framework\TestCase;

class AgencyHostingV1WebsitesWebsiteListItemResourceDetailsTest extends TestCase
{

    public static function setUpBeforeClass(): void
    {
    }

    public function setUp(): void
    {
    }

    public function tearDown(): void
    {
    }

    public static function tearDownAfterClass(): void
    {
    }

    public function testAgencyHostingV1WebsitesWebsiteListItemResourceDetails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyUid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyIpv4()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyFlavor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyUsername()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyState()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyCreatedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertySettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyWordpress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyDomains()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyPreviewDomain()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyProcesses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyHorizonsUuid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyVhost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyUuid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyTitle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyPort()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyRuntime()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
