<?php

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.54.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Test\Model;

use PHPUnit\Framework\TestCase;

class HostingV1GitGitRepositoryResourceTest extends TestCase
{

    public static function setUpBeforeClass(): void
    {
    }

    public function setUp(): void
    {
    }

    public function tearDown(): void
    {
    }

    public static function tearDownAfterClass(): void
    {
    }

    public function testHostingV1GitGitRepositoryResource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyFullName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyOwner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyIsPrivate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyHtmlUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyCloneUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyDefaultBranch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
