<?php

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.34.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Test\Model;

use PHPUnit\Framework\TestCase;

class ReachV1CampaignsCampaignDetailsResourceTest extends TestCase
{

    public static function setUpBeforeClass(): void
    {
    }

    public function setUp(): void
    {
    }

    public function tearDown(): void
    {
    }

    public static function tearDownAfterClass(): void
    {
    }

    public function testReachV1CampaignsCampaignDetailsResource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyUuid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyTitle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertySubject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertySenderName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertySenderEmail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyTemplateUuid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyFailureReason()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyIsSmartSend()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyIsAllContacts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyDelivery()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertySegmentUuids()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyCreatedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyUpdatedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertySentAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyScheduledAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
