<?php

/**
 * Hostinger API PHP SDK
 *
 * API Version: 1.5.0
 * @url https://github.com/hostinger/api-php-sdk
 *
 * NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
 * If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
 */

namespace Hostinger\Test\Model;

use PHPUnit\Framework\TestCase;

class ReachV1ProfilesDomainsDnsStatusResourceTest extends TestCase
{

    public static function setUpBeforeClass(): void
    {
    }

    public function setUp(): void
    {
    }

    public function tearDown(): void
    {
    }

    public static function tearDownAfterClass(): void
    {
    }

    public function testReachV1ProfilesDomainsDnsStatusResource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyDomain()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyMx()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertySpf()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyDkim()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    public function testPropertyDmarc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
